// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAppConfig = "app_config"

// AppConfig mapped from table <app_config>
type AppConfig struct {
	ID           *int32 `gorm:"column:id;primaryKey" json:"id"`
	DefaultsJSON string `gorm:"column:defaults_json;not null" json:"defaults_json"`
	UpdatedAt    string `gorm:"column:updated_at;not null;default:datetime('now'))" json:"updated_at"`
}

// TableName AppConfig's table name
func (*AppConfig) TableName() string {
	return TableNameAppConfig
}
