// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCrawlRun = "crawl_runs"

// CrawlRun mapped from table <crawl_runs>
type CrawlRun struct {
	ID           *string `gorm:"column:id;primaryKey" json:"id"`
	WorkspaceID  string  `gorm:"column:workspace_id;not null" json:"workspace_id"`
	Mode         int32   `gorm:"column:mode;not null" json:"mode"`
	Status       *string `gorm:"column:status;type:TEXT" json:"status"`
	StartedAt    string  `gorm:"column:started_at;not null" json:"started_at"`
	FinishedAt   *string `gorm:"column:finished_at" json:"finished_at"`
	SummaryJSON  *string `gorm:"column:summary_json" json:"summary_json"`
	ErrorMessage *string `gorm:"column:error_message" json:"error_message"`
}

// TableName CrawlRun's table name
func (*CrawlRun) TableName() string {
	return TableNameCrawlRun
}
