// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDomainSetting = "domain_settings"

// DomainSetting mapped from table <domain_settings>
type DomainSetting struct {
	WorkspaceID  string `gorm:"column:workspace_id;primaryKey" json:"workspace_id"`
	Host         string `gorm:"column:host;primaryKey" json:"host"`
	SettingsJSON string `gorm:"column:settings_json;not null;default:'{}'" json:"settings_json"`
}

// TableName DomainSetting's table name
func (*DomainSetting) TableName() string {
	return TableNameDomainSetting
}
