// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGraphNode = "graph_nodes"

// GraphNode mapped from table <graph_nodes>
type GraphNode struct {
	WorkspaceID      string  `gorm:"column:workspace_id;primaryKey" json:"workspace_id"`
	ID               string  `gorm:"column:id;primaryKey" json:"id"`
	URLNormalized    string  `gorm:"column:url_normalized;not null" json:"url_normalized"`
	Label            string  `gorm:"column:label;not null" json:"label"`
	PositionX        float64 `gorm:"column:position_x;not null" json:"position_x"`
	PositionY        float64 `gorm:"column:position_y;not null" json:"position_y"`
	UserPositioned   int32   `gorm:"column:user_positioned;not null" json:"user_positioned"`
	NodeSettingsJSON string  `gorm:"column:node_settings_json;not null;default:'{}'" json:"node_settings_json"`
	CrawlExclude     int32   `gorm:"column:crawl_exclude;not null" json:"crawl_exclude"`
	Status           *string `gorm:"column:status;type:TEXT" json:"status"`
	LastError        *string `gorm:"column:last_error" json:"last_error"`
	Origin           string  `gorm:"column:origin;not null;default:'crawl' CHECK (origin IN ('crawl', 'manual'))" json:"origin"`
}

// TableName GraphNode's table name
func (*GraphNode) TableName() string {
	return TableNameGraphNode
}
