// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGraphUIState = "graph_ui_state"

// GraphUIState mapped from table <graph_ui_state>
type GraphUIState struct {
	WorkspaceID          *string `gorm:"column:workspace_id;primaryKey" json:"workspace_id"`
	CollapsedNodeIdsJSON string  `gorm:"column:collapsed_node_ids_json;not null;default:'{"collapsed":[],"expandedDetail":[]}'" json:"collapsed_node_ids_json"`
}

// TableName GraphUIState's table name
func (*GraphUIState) TableName() string {
	return TableNameGraphUIState
}
