// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
)

import (
	_ "github.com/golang-migrate/migrate/v4/database/sqlite"
)

// Injectors from wire.go:

func InitializeWire(ctx context.Context) (*Application, func(), error) {
	string2, err := ProvideDBPath()
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := ProvideDB(string2)
	if err != nil {
		return nil, nil, err
	}
	repository := ProvideRepository(db)
	appConfigService := ProvideAppConfigService(repository)
	workspaceService := ProvideWorkspaceService(repository)
	resultsService := ProvideResultsService(repository, workspaceService)
	diffService := ProvideDiffService(repository, workspaceService)
	crawlPersistService := ProvideCrawlPersistService(repository)
	storeService := ProvideStoreService(appConfigService, workspaceService, resultsService, diffService, crawlPersistService)
	projectFileService := ProvideProjectFileService(workspaceService)
	projectService := ProvideProjectService(projectFileService, workspaceService)
	scraperService := ProvideScraperService(crawlPersistService)
	application, cleanup2, err := ProvideApplication(storeService, projectService, scraperService, db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return application, func() {
		cleanup2()
		cleanup()
	}, nil
}
