// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CheckForUpdatesResult は手動更新確認の結果。
 */
export class CheckForUpdatesResult {
    /**
     * Status は up_to_date / available（ダイアログ表示後）など。
     */
    "status": string;

    /**
     * Action は PromptUpdate の結果（confirmed / open_release / dismissed）。
     */
    "action"?: string;

    /**
     * Version は対象リリース版。
     */
    "version"?: string;

    /**
     * ReleaseURL は GitHub リリースページ URL。
     */
    "releaseURL"?: string;

    /** Creates a new CheckForUpdatesResult instance. */
    constructor($$source: Partial<CheckForUpdatesResult> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CheckForUpdatesResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CheckForUpdatesResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CheckForUpdatesResult($$parsedSource as Partial<CheckForUpdatesResult>);
    }
}

/**
 * UpdatePromptResult は更新確認ウィンドウの結果。
 */
export class UpdatePromptResult {
    /**
     * Action は confirmed / open_release / dismissed。
     */
    "action": string;

    /**
     * Version は対象リリース版。
     */
    "version"?: string;

    /**
     * ReleaseURL は GitHub リリースページ URL。
     */
    "releaseURL"?: string;

    /** Creates a new UpdatePromptResult instance. */
    constructor($$source: Partial<UpdatePromptResult> = {}) {
        if (!("action" in $$source)) {
            this["action"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdatePromptResult instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdatePromptResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdatePromptResult($$parsedSource as Partial<UpdatePromptResult>);
    }
}

/**
 * UpdatePromptSnapshot は更新確認ウィンドウ表示用スナップショット。
 */
export class UpdatePromptSnapshot {
    /**
     * Version は利用可能なリリース版。
     */
    "version": string;

    /**
     * ReleaseURL は GitHub リリースページ URL。
     */
    "releaseURL": string;

    /** Creates a new UpdatePromptSnapshot instance. */
    constructor($$source: Partial<UpdatePromptSnapshot> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("releaseURL" in $$source)) {
            this["releaseURL"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdatePromptSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdatePromptSnapshot {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdatePromptSnapshot($$parsedSource as Partial<UpdatePromptSnapshot>);
    }
}

/**
 * UpdateStatus はフロント向けの更新状態。
 */
export class UpdateStatus {
    /**
     * Status は up_to_date / available / ready / unavailable。
     */
    "status": string;

    /**
     * Version は対象リリース版（available / ready のとき）。
     */
    "version"?: string;

    /**
     * ReleaseURL は GitHub リリースページ URL。
     */
    "releaseURL"?: string;

    /** Creates a new UpdateStatus instance. */
    constructor($$source: Partial<UpdateStatus> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateStatus($$parsedSource as Partial<UpdateStatus>);
    }
}
