// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProjectService は .scrb 入出力 Wails RPC（debug ログ付き殻）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";

/**
 * OpenScrb は ProjectServiceAPI を実装する。
 */
export function OpenScrb(): $CancellablePromise<model$0.OpenScrbResponse> {
    return $Call.ByID(3278929463).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SaveScrb は ProjectServiceAPI を実装する。
 */
export function SaveScrb(workspaceID: string, includeResults: boolean): $CancellablePromise<void> {
    return $Call.ByID(3180281898, workspaceID, includeResults);
}

/**
 * SetApp は ProjectServiceAPI を実装する。
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2645629862, app);
}

// Private type creation functions
const $$createType0 = model$0.OpenScrbResponse.createFrom;
