// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ScraperService は backend crawler を駆動し Wails Event で進捗を配信する。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";

/**
 * FetchRobotsTxt は host の robots.txt を取得する。
 * 
 * baseURL は scheme 推定用（ノード URL）。空の場合は https を使用する。
 * appDefaults と wsSettings は MergeUIConfigLayers 用の PartialConfig JSON。
 */
export function FetchRobotsTxt(host: string, baseURL: string, appDefaults: json$0.RawMessage, wsSettings: json$0.RawMessage): $CancellablePromise<model$0.RobotsTxtInfoDTO> {
    return $Call.ByID(3139220193, host, baseURL, appDefaults, wsSettings).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * PauseCrawl は実行中 crawl を一時停止する。
 */
export function PauseCrawl(runID: string): $CancellablePromise<void> {
    return $Call.ByID(2633759127, runID);
}

/**
 * ResumeCrawl は一時停止中 crawl を再開する。
 */
export function ResumeCrawl(runID: string): $CancellablePromise<void> {
    return $Call.ByID(3420340728, runID);
}

/**
 * SetApp は Wails App を後から注入する（Event 発火用）。
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(694879137, app);
}

/**
 * StartCrawl はクロールを非同期で開始し runId を返す。
 */
export function StartCrawl(req: model$0.StartCrawlRequest): $CancellablePromise<string> {
    return $Call.ByID(981142773, req);
}

/**
 * StopCrawl は実行中 crawl をキャンセルする。
 */
export function StopCrawl(runID: string): $CancellablePromise<void> {
    return $Call.ByID(3550499157, runID);
}

// Private type creation functions
const $$createType0 = model$0.RobotsTxtInfoDTO.createFrom;
