// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ScraperService は backend crawler を駆動し Wails Event で進捗を配信する（debug ログ付き殻）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";

/**
 * FetchRobotsTxt は ScraperServiceAPI を実装する。
 */
export function FetchRobotsTxt(host: string, baseURL: string, appDefaults: json$0.RawMessage, wsSettings: json$0.RawMessage): $CancellablePromise<model$0.RobotsTxtInfoDTO> {
    return $Call.ByID(3139220193, host, baseURL, appDefaults, wsSettings).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * PauseCrawl は ScraperServiceAPI を実装する。
 */
export function PauseCrawl(runID: string): $CancellablePromise<void> {
    return $Call.ByID(2633759127, runID);
}

/**
 * ResumeCrawl は ScraperServiceAPI を実装する。
 */
export function ResumeCrawl(runID: string): $CancellablePromise<void> {
    return $Call.ByID(3420340728, runID);
}

/**
 * SetApp は ScraperServiceAPI を実装する。
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(694879137, app);
}

/**
 * StartCrawl は ScraperServiceAPI を実装する。
 */
export function StartCrawl(req: model$0.StartCrawlRequest): $CancellablePromise<string> {
    return $Call.ByID(981142773, req);
}

/**
 * StopCrawl は ScraperServiceAPI を実装する。
 */
export function StopCrawl(runID: string): $CancellablePromise<void> {
    return $Call.ByID(3550499157, runID);
}

// Private type creation functions
const $$createType0 = model$0.RobotsTxtInfoDTO.createFrom;
