// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StoreService は Wails 公開 Store RPC（debug ログ付き殻）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";

/**
 * AppendNodeResult は StoreServiceAPI を実装する。
 */
export function AppendNodeResult(req: model$0.AppendNodeResultRequest): $CancellablePromise<void> {
    return $Call.ByID(3338613912, req);
}

/**
 * BeginCrawlRun は StoreServiceAPI を実装する。
 */
export function BeginCrawlRun(req: model$0.BeginCrawlRunRequest): $CancellablePromise<void> {
    return $Call.ByID(2037716558, req);
}

/**
 * Bootstrap は StoreServiceAPI を実装する。
 */
export function Bootstrap(): $CancellablePromise<void> {
    return $Call.ByID(985413417);
}

/**
 * DeleteResults は StoreServiceAPI を実装する。
 */
export function DeleteResults(workspaceID: string, nodeIDs: string[]): $CancellablePromise<void> {
    return $Call.ByID(1479558768, workspaceID, nodeIDs);
}

/**
 * DeleteWorkspace は StoreServiceAPI を実装する。
 */
export function DeleteWorkspace(id: string): $CancellablePromise<void> {
    return $Call.ByID(4143795755, id);
}

/**
 * DuplicateWorkspace は StoreServiceAPI を実装する。
 */
export function DuplicateWorkspace(req: model$0.DuplicateWorkspaceRequest): $CancellablePromise<model$0.WorkspaceDTO | null> {
    return $Call.ByID(990842695, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * FinishCrawlRun は StoreServiceAPI を実装する。
 */
export function FinishCrawlRun(req: model$0.FinishCrawlRunRequest): $CancellablePromise<void> {
    return $Call.ByID(3267595186, req);
}

/**
 * GetAppDefaults は StoreServiceAPI を実装する。
 */
export function GetAppDefaults(): $CancellablePromise<json$0.RawMessage> {
    return $Call.ByID(2994918004);
}

/**
 * GetExportSession は StoreServiceAPI を実装する。
 */
export function GetExportSession(): $CancellablePromise<model$0.ExportSessionRequest> {
    return $Call.ByID(3088241959).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetGraphNodeStatuses は StoreServiceAPI を実装する。
 */
export function GetGraphNodeStatuses(workspaceID: string, nodeIDs: string[]): $CancellablePromise<model$0.GraphNodeStatusDTO[]> {
    return $Call.ByID(1086371375, workspaceID, nodeIDs).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetMaximizedNodeResult は StoreServiceAPI を実装する。
 */
export function GetMaximizedNodeResult(): $CancellablePromise<model$0.MaximizedNodeResultRequest> {
    return $Call.ByID(790067210).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetNodeDiffDetail は StoreServiceAPI を実装する。
 */
export function GetNodeDiffDetail(workspaceID: string, nodeID: string): $CancellablePromise<model$0.NodeDiffDetailDTO> {
    return $Call.ByID(1971368189, workspaceID, nodeID).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetNodeDiffViewerSession は StoreServiceAPI を実装する。
 */
export function GetNodeDiffViewerSession(): $CancellablePromise<model$0.NodeDiffViewerRequest> {
    return $Call.ByID(2980533114).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetNodeResult は StoreServiceAPI を実装する。
 */
export function GetNodeResult(workspaceID: string, nodeID: string): $CancellablePromise<model$0.CrawlResultDTO | null> {
    return $Call.ByID(1231862750, workspaceID, nodeID).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetNodeResults は StoreServiceAPI を実装する。
 */
export function GetNodeResults(workspaceID: string, nodeIDs: string[]): $CancellablePromise<model$0.CrawlResultDTO[]> {
    return $Call.ByID(1126920535, workspaceID, nodeIDs).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * GetWorkspaceDiff は StoreServiceAPI を実装する。
 */
export function GetWorkspaceDiff(workspaceID: string): $CancellablePromise<model$0.WorkspaceDiffDTO> {
    return $Call.ByID(1767944683, workspaceID).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * ListWorkspaces は StoreServiceAPI を実装する。
 */
export function ListWorkspaces(): $CancellablePromise<model$0.WorkspaceListItemDTO[]> {
    return $Call.ByID(737251475).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * LoadWorkspace は StoreServiceAPI を実装する。
 */
export function LoadWorkspace(id: string): $CancellablePromise<model$0.WorkspaceDTO | null> {
    return $Call.ByID(1245564714, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * MergeResults は StoreServiceAPI を実装する。
 */
export function MergeResults(workspaceID: string, nodeIDs: string[], formats: string[]): $CancellablePromise<model$0.MergeResultsResponseDTO> {
    return $Call.ByID(1679166919, workspaceID, nodeIDs, formats).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * PatchGraphNodePositions は StoreServiceAPI を実装する。
 */
export function PatchGraphNodePositions(req: model$0.PatchGraphNodePositionsRequest): $CancellablePromise<void> {
    return $Call.ByID(617561921, req);
}

/**
 * PatchGraphNodeStatus は StoreServiceAPI を実装する。
 */
export function PatchGraphNodeStatus(req: model$0.PatchGraphNodeStatusRequest): $CancellablePromise<void> {
    return $Call.ByID(4080782077, req);
}

/**
 * SaveAppDefaults は StoreServiceAPI を実装する。
 */
export function SaveAppDefaults(config: json$0.RawMessage): $CancellablePromise<model$0.SaveSettingsResponseDTO> {
    return $Call.ByID(2781423509, config).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * SaveExportFile は StoreServiceAPI を実装する。
 */
export function SaveExportFile(content: string, defaultExt: string): $CancellablePromise<void> {
    return $Call.ByID(2344457880, content, defaultExt);
}

/**
 * SaveExportZip は StoreServiceAPI を実装する。
 */
export function SaveExportZip(entries: model$0.ExportZipEntryDTO[], defaultExt: string): $CancellablePromise<void> {
    return $Call.ByID(2925762301, entries, defaultExt);
}

/**
 * SaveNodeSettings は StoreServiceAPI を実装する。
 */
export function SaveNodeSettings(workspaceID: string, nodeID: string, settings: json$0.RawMessage): $CancellablePromise<model$0.SaveSettingsResponseDTO> {
    return $Call.ByID(3704504073, workspaceID, nodeID, settings).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * SaveResults は StoreServiceAPI を実装する。
 */
export function SaveResults(workspaceID: string, nodeIDs: string[]): $CancellablePromise<void> {
    return $Call.ByID(1321913430, workspaceID, nodeIDs);
}

/**
 * SaveResultsSnapshot は StoreServiceAPI を実装する。
 */
export function SaveResultsSnapshot(workspaceID: string, runID: string): $CancellablePromise<string> {
    return $Call.ByID(2727732938, workspaceID, runID);
}

/**
 * SaveWorkspace は StoreServiceAPI を実装する。
 */
export function SaveWorkspace(ws: model$0.WorkspaceDTO): $CancellablePromise<void> {
    return $Call.ByID(1336534245, ws);
}

/**
 * SaveWorkspaceSettings は StoreServiceAPI を実装する。
 */
export function SaveWorkspaceSettings(workspaceID: string, settings: json$0.RawMessage): $CancellablePromise<model$0.SaveSettingsResponseDTO> {
    return $Call.ByID(1553310216, workspaceID, settings).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * SetApp は StoreServiceAPI を実装する。
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3115946214, app);
}

/**
 * SetAppDefaults は StoreServiceAPI を実装する。
 */
export function SetAppDefaults(config: json$0.RawMessage): $CancellablePromise<void> {
    return $Call.ByID(2075852616, config);
}

/**
 * ShowExportWindow は StoreServiceAPI を実装する。
 */
export function ShowExportWindow(req: model$0.ExportSessionRequest): $CancellablePromise<void> {
    return $Call.ByID(3382306870, req);
}

/**
 * ShowMaximizedNodeResult は StoreServiceAPI を実装する。
 */
export function ShowMaximizedNodeResult(req: model$0.MaximizedNodeResultRequest): $CancellablePromise<void> {
    return $Call.ByID(916939843, req);
}

/**
 * ShowNodeDiffWindow は StoreServiceAPI を実装する。
 */
export function ShowNodeDiffWindow(req: model$0.NodeDiffViewerRequest): $CancellablePromise<void> {
    return $Call.ByID(4173351135, req);
}

/**
 * UpdateNodeResult は StoreServiceAPI を実装する。
 */
export function UpdateNodeResult(req: model$0.UpdateNodeResultRequest): $CancellablePromise<model$0.CrawlResultDTO | null> {
    return $Call.ByID(3146172057, req).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * UpsertDiscoveredGraph は StoreServiceAPI を実装する。
 */
export function UpsertDiscoveredGraph(req: model$0.UpsertDiscoveredGraphRequest): $CancellablePromise<void> {
    return $Call.ByID(1887043808, req);
}

// Private type creation functions
const $$createType0 = model$0.WorkspaceDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.ExportSessionRequest.createFrom;
const $$createType3 = model$0.GraphNodeStatusDTO.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = model$0.MaximizedNodeResultRequest.createFrom;
const $$createType6 = model$0.NodeDiffDetailDTO.createFrom;
const $$createType7 = model$0.NodeDiffViewerRequest.createFrom;
const $$createType8 = model$0.CrawlResultDTO.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($$createType8);
const $$createType11 = model$0.WorkspaceDiffDTO.createFrom;
const $$createType12 = model$0.WorkspaceListItemDTO.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = model$0.MergeResultsResponseDTO.createFrom;
const $$createType15 = model$0.SaveSettingsResponseDTO.createFrom;
