// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService は Wails updater の手動確認 RPC。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckAndInstall は更新を確認し、利用可能ならダウンロードしてステージする。
 * 
 * WindowNone 構成では Wails 標準 UI を開かず、結果を UpdateCheckResult で返す。
 */
export function CheckAndInstall(): $CancellablePromise<$models.UpdateCheckResult> {
    return $Call.ByID(4194660025).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetApp は Wails App を後から注入する。
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3332553932, app);
}

// Private type creation functions
const $$createType0 = $models.UpdateCheckResult.createFrom;
