// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService は Wails updater の手動確認 RPC。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyUpdate は pending 更新をダウンロードしてステージし、exe を差し替えて再起動する。
 */
export function ApplyUpdate(): $CancellablePromise<void> {
    return $Call.ByID(2251658320);
}

/**
 * Check は更新を確認し、利用可能なら pending に保持する（ダウンロードはしない）。
 */
export function Check(): $CancellablePromise<$models.UpdateStatus> {
    return $Call.ByID(77746993).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CheckForUpdates は手動更新確認（Check → 利用可能なら PromptUpdate）を行う。
 */
export function CheckForUpdates(): $CancellablePromise<$models.CheckForUpdatesResult> {
    return $Call.ByID(55604786).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CheckOnStartup は起動時の更新確認を行い、利用可能ならイベントを発火する。
 */
export function CheckOnStartup(): $CancellablePromise<void> {
    return $Call.ByID(3059510365);
}

/**
 * GetStatus は現在の更新状態を返す。
 */
export function GetStatus(): $CancellablePromise<$models.UpdateStatus> {
    return $Call.ByID(3872011227).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * PromptUpdate はネイティブダイアログで更新確認を行う。
 */
export function PromptUpdate(): $CancellablePromise<$models.UpdatePromptResult> {
    return $Call.ByID(1284834148).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SetApp は Wails App を後から注入する。
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3332553932, app);
}

/**
 * StartPeriodicCheck は interval ごとに Check のみを実行するバックグラウンドループを開始する。
 */
export function StartPeriodicCheck(interval: time$0.Duration): $CancellablePromise<void> {
    return $Call.ByID(1087651044, interval);
}

// Private type creation functions
const $$createType0 = $models.UpdateStatus.createFrom;
const $$createType1 = $models.CheckForUpdatesResult.createFrom;
const $$createType2 = $models.UpdatePromptResult.createFrom;
