// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService は Wails updater の手動確認 RPC（debug ログ付き殻）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyUpdate は UpdateServiceAPI を実装する。
 */
export function ApplyUpdate(): $CancellablePromise<void> {
    return $Call.ByID(2251658320);
}

/**
 * Check は UpdateServiceAPI を実装する。
 */
export function Check(): $CancellablePromise<$models.UpdateStatus> {
    return $Call.ByID(77746993).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CheckForUpdates は UpdateServiceAPI を実装する。
 */
export function CheckForUpdates(): $CancellablePromise<$models.CheckForUpdatesResult> {
    return $Call.ByID(55604786).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CheckOnStartup は UpdateServiceAPI を実装する。
 */
export function CheckOnStartup(): $CancellablePromise<void> {
    return $Call.ByID(3059510365);
}

/**
 * GetStatus は UpdateServiceAPI を実装する。
 */
export function GetStatus(): $CancellablePromise<$models.UpdateStatus> {
    return $Call.ByID(3872011227).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetUpdatePromptSnapshot は UpdateServiceAPI を実装する。
 */
export function GetUpdatePromptSnapshot(): $CancellablePromise<$models.UpdatePromptSnapshot> {
    return $Call.ByID(325402770).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * PromptUpdate は UpdateServiceAPI を実装する。
 */
export function PromptUpdate(): $CancellablePromise<$models.UpdatePromptResult> {
    return $Call.ByID(1284834148).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * SetApp は UpdateServiceAPI を実装する。
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3332553932, app);
}

/**
 * StartPeriodicCheck は UpdateServiceAPI を実装する。
 */
export function StartPeriodicCheck(interval: time$0.Duration): $CancellablePromise<void> {
    return $Call.ByID(1087651044, interval);
}

/**
 * SubmitUpdatePrompt は UpdateServiceAPI を実装する。
 */
export function SubmitUpdatePrompt(action: string): $CancellablePromise<void> {
    return $Call.ByID(1560439932, action);
}

// Private type creation functions
const $$createType0 = $models.UpdateStatus.createFrom;
const $$createType1 = $models.CheckForUpdatesResult.createFrom;
const $$createType2 = $models.UpdatePromptSnapshot.createFrom;
const $$createType3 = $models.UpdatePromptResult.createFrom;
