// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"scraperbot/internal/domain/model"
)

// Injectors from wire.go:

// Initialize は Config と context から Application と cleanup 関数を構築する。
func Initialize(ctx context.Context, cfg *model.Config) (*Application, func(), error) {
	host := ProvideHost(cfg)
	registry := ProvideRegistry()
	kernel, cleanup, err := ProvideKernel(ctx, cfg, host, registry)
	if err != nil {
		return nil, nil, err
	}
	scrape := ProvideScrape(kernel)
	cache := ProvideRobotsCache(kernel)
	crawlerFactory := ProvideCrawlerFactory(kernel, cache)
	fileWriter := ProvideFileWriter(cfg)
	fileResultSink := &FileResultSink{
		Writer: fileWriter,
	}
	crawl := ProvideCrawl(crawlerFactory, fileResultSink)
	application := &Application{
		Kernel:     kernel,
		Scrape:     scrape,
		Crawl:      crawl,
		FileWriter: fileWriter,
	}
	return application, func() {
		cleanup()
	}, nil
}
