// Code generated by gowrap. DO NOT EDIT.
// template: templates\slog_debug.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package runner

//go:generate gowrap gen -p meguri/pkg/runner -i ChromiumShutdown -t templates\slog_debug.gotmpl -o chromium_shutdown_with_debug_log.go -l ""

import (
	"log/slog"
)

// ChromiumShutdownWithDebugLog は ChromiumShutdown に debug ログを付与するデコレータ。
type ChromiumShutdownWithDebugLog struct {
	_base ChromiumShutdown
}

// NewChromiumShutdownWithDebugLog は base を debug ログ付きでラップする。
func NewChromiumShutdownWithDebugLog(base ChromiumShutdown) ChromiumShutdownWithDebugLog {
	return ChromiumShutdownWithDebugLog{_base: base}
}

// CloseChromiumBrowsers は ChromiumShutdown を実装する。
func (_d ChromiumShutdownWithDebugLog) CloseChromiumBrowsers() {
	slog.Debug("runner: ChromiumShutdown.CloseChromiumBrowsers call")
	defer func() {
		slog.Debug("runner: ChromiumShutdown.CloseChromiumBrowsers finished")
	}()
	_d._base.CloseChromiumBrowsers()
	return
}
