// Code generated by gowrap. DO NOT EDIT.
// template: templates\slog_debug.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package runner

//go:generate gowrap gen -p meguri/pkg/runner -i Crawler -t templates\slog_debug.gotmpl -o crawler_with_debug_log.go -l ""

import (
	"context"
	"log/slog"
)

// CrawlerWithDebugLog は Crawler に debug ログを付与するデコレータ。
type CrawlerWithDebugLog struct {
	_base Crawler
}

// NewCrawlerWithDebugLog は base を debug ログ付きでラップする。
func NewCrawlerWithDebugLog(base Crawler) CrawlerWithDebugLog {
	return CrawlerWithDebugLog{_base: base}
}

// CrawlWithProgress は Crawler を実装する。
func (_d CrawlerWithDebugLog) CrawlWithProgress(ctx context.Context, cfg *Config, seeds []string, progress ProgressSink, opts *RunOptions) (cp1 *CrawlStats, err error) {
	slog.DebugContext(ctx, "runner: Crawler.CrawlWithProgress call", slog.Any("params", debugLogMap(map[string]interface{}{
		"ctx":      ctx,
		"cfg":      cfg,
		"seeds":    seeds,
		"progress": progress,
		"opts":     opts})))
	defer func() {
		slog.DebugContext(ctx, "runner: Crawler.CrawlWithProgress return", slog.Any("results", debugLogMap(map[string]interface{}{
			"cp1": cp1,
			"err": err})))
	}()
	return _d._base.CrawlWithProgress(ctx, cfg, seeds, progress, opts)
}
