// Code generated by gowrap. DO NOT EDIT.
// template: templates\slog_debug.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package runner

//go:generate gowrap gen -p meguri/pkg/runner -i FetchLimiterPreparer -t templates\slog_debug.gotmpl -o fetch_limit_preparer_with_debug_log.go -l ""

import (
	"context"
	"log/slog"
	"meguri/internal/core/fetchlimit"
	"meguri/internal/domain/model"
)

// FetchLimiterPreparerWithDebugLog は FetchLimiterPreparer に debug ログを付与するデコレータ。
type FetchLimiterPreparerWithDebugLog struct {
	_base FetchLimiterPreparer
}

// NewFetchLimiterPreparerWithDebugLog は base を debug ログ付きでラップする。
func NewFetchLimiterPreparerWithDebugLog(base FetchLimiterPreparer) FetchLimiterPreparerWithDebugLog {
	return FetchLimiterPreparerWithDebugLog{_base: base}
}

// PrepareFetchLimiter は FetchLimiterPreparer を実装する。
func (_d FetchLimiterPreparerWithDebugLog) PrepareFetchLimiter(ctx context.Context, cfg *model.Config, opts *RunOptions) (fp1 *fetchlimit.FetchLimiter) {
	slog.DebugContext(ctx, "runner: FetchLimiterPreparer.PrepareFetchLimiter call", slog.Any("params", debugLogMap(map[string]interface{}{
		"ctx":  ctx,
		"cfg":  cfg,
		"opts": opts})))
	defer func() {
		slog.DebugContext(ctx, "runner: FetchLimiterPreparer.PrepareFetchLimiter return", slog.Any("results", debugLogMap(map[string]interface{}{
			"fp1": fp1})))
	}()
	return _d._base.PrepareFetchLimiter(ctx, cfg, opts)
}
