// Code generated by gowrap. DO NOT EDIT.
// template: templates\slog_debug.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package runner

//go:generate gowrap gen -p meguri/pkg/runner -i RobotsFetcher -t templates\slog_debug.gotmpl -o robots_fetcher_with_debug_log.go -l ""

import (
	"context"
	"encoding/json"
	"log/slog"
)

// RobotsFetcherWithDebugLog は RobotsFetcher に debug ログを付与するデコレータ。
type RobotsFetcherWithDebugLog struct {
	_base RobotsFetcher
}

// NewRobotsFetcherWithDebugLog は base を debug ログ付きでラップする。
func NewRobotsFetcherWithDebugLog(base RobotsFetcher) RobotsFetcherWithDebugLog {
	return RobotsFetcherWithDebugLog{_base: base}
}

// FetchRobotsTxt は RobotsFetcher を実装する。
func (_d RobotsFetcherWithDebugLog) FetchRobotsTxt(ctx context.Context, host string, baseURL string, configLayers ...json.RawMessage) (r1 RobotsTxtResult, err error) {
	slog.DebugContext(ctx, "runner: RobotsFetcher.FetchRobotsTxt call", slog.Any("params", debugLogMap(map[string]interface{}{
		"ctx":          ctx,
		"host":         host,
		"baseURL":      baseURL,
		"configLayers": configLayers})))
	defer func() {
		slog.DebugContext(ctx, "runner: RobotsFetcher.FetchRobotsTxt return", slog.Any("results", debugLogMap(map[string]interface{}{
			"r1":  r1,
			"err": err})))
	}()
	return _d._base.FetchRobotsTxt(ctx, host, baseURL, configLayers...)
}
