// Code generated by gowrap. DO NOT EDIT.
// template: templates\slog_debug.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package runner

//go:generate gowrap gen -p meguri/pkg/runner -i Scraper -t templates\slog_debug.gotmpl -o scraper_with_debug_log.go -l ""

import (
	"context"
	"log/slog"
)

// ScraperWithDebugLog は Scraper に debug ログを付与するデコレータ。
type ScraperWithDebugLog struct {
	_base Scraper
}

// NewScraperWithDebugLog は base を debug ログ付きでラップする。
func NewScraperWithDebugLog(base Scraper) ScraperWithDebugLog {
	return ScraperWithDebugLog{_base: base}
}

// ScrapeWithConfig は Scraper を実装する。
func (_d ScraperWithDebugLog) ScrapeWithConfig(ctx context.Context, rawURL string, cfg *Config, progress ProgressSink, opts *RunOptions) (rp1 *Result, err error) {
	slog.DebugContext(ctx, "runner: Scraper.ScrapeWithConfig call", slog.Any("params", debugLogMap(map[string]interface{}{
		"ctx":      ctx,
		"rawURL":   rawURL,
		"cfg":      cfg,
		"progress": progress,
		"opts":     opts})))
	defer func() {
		slog.DebugContext(ctx, "runner: Scraper.ScrapeWithConfig return", slog.Any("results", debugLogMap(map[string]interface{}{
			"rp1": rp1,
			"err": err})))
	}()
	return _d._base.ScrapeWithConfig(ctx, rawURL, cfg, progress, opts)
}
