// Code generated by gowrap. DO NOT EDIT.
// template: templates\slog_debug.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package runner

//go:generate gowrap gen -p meguri/pkg/runner -i UIConfigurator -t templates\slog_debug.gotmpl -o uiconfigurator_with_debug_log.go -l ""

import (
	"encoding/json"
	"log/slog"
	"meguri/internal/domain/model"
)

// UIConfiguratorWithDebugLog は UIConfigurator に debug ログを付与するデコレータ。
type UIConfiguratorWithDebugLog struct {
	_base UIConfigurator
}

// NewUIConfiguratorWithDebugLog は base を debug ログ付きでラップする。
func NewUIConfiguratorWithDebugLog(base UIConfigurator) UIConfiguratorWithDebugLog {
	return UIConfiguratorWithDebugLog{_base: base}
}

// DeriveContentFormats は UIConfigurator を実装する。
func (_d UIConfiguratorWithDebugLog) DeriveContentFormats(cfg *model.Config) {
	slog.Debug("runner: UIConfigurator.DeriveContentFormats call", slog.Any("params", debugLogMap(map[string]interface{}{
		"cfg": cfg})))
	defer func() {
		slog.Debug("runner: UIConfigurator.DeriveContentFormats finished")
	}()
	_d._base.DeriveContentFormats(cfg)
	return
}

// MergeUIConfigLayers は UIConfigurator を実装する。
func (_d UIConfiguratorWithDebugLog) MergeUIConfigLayers(layers ...json.RawMessage) (r1 json.RawMessage, err error) {
	slog.Debug("runner: UIConfigurator.MergeUIConfigLayers call", slog.Any("params", debugLogMap(map[string]interface{}{
		"layers": layers})))
	defer func() {
		slog.Debug("runner: UIConfigurator.MergeUIConfigLayers return", slog.Any("results", debugLogMap(map[string]interface{}{
			"r1":  r1,
			"err": err})))
	}()
	return _d._base.MergeUIConfigLayers(layers...)
}

// ParseUIConfig は UIConfigurator を実装する。
func (_d UIConfiguratorWithDebugLog) ParseUIConfig(raw json.RawMessage) (cp1 *model.Config, err error) {
	slog.Debug("runner: UIConfigurator.ParseUIConfig call", slog.Any("params", debugLogMap(map[string]interface{}{
		"raw": raw})))
	defer func() {
		slog.Debug("runner: UIConfigurator.ParseUIConfig return", slog.Any("results", debugLogMap(map[string]interface{}{
			"cp1": cp1,
			"err": err})))
	}()
	return _d._base.ParseUIConfig(raw)
}
