// Code generated by gowrap. DO NOT EDIT.
// template: templates\slog_debug_slow.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package wails_service

//go:generate gowrap gen -p meguri-app/internal/usecase/wails_service -i ProjectServiceAPI -t templates\slog_debug_slow.gotmpl -o project_service_with_debug_log.go -v ServiceName=ProjectService -v DecoratorName=ProjectServiceWithDebugLog -l ""

import (
	"log/slog"
	"meguri-app/internal/model"
	"time"

	"github.com/wailsapp/wails/v3/pkg/application"
)

// ProjectServiceWithDebugLog は ProjectServiceAPI に debug ログを付与するデコレータ。
type ProjectServiceWithDebugLog struct {
	_base ProjectServiceAPI
}

// NewProjectServiceWithDebugLog は base を debug ログ付きでラップする。
func NewProjectServiceWithDebugLog(base ProjectServiceAPI) ProjectServiceWithDebugLog {
	return ProjectServiceWithDebugLog{_base: base}
}

// OpenScrb は ProjectServiceAPI を実装する。
func (_d ProjectServiceWithDebugLog) OpenScrb() (o1 model.OpenScrbResponse, err error) {
	slog.Debug("usecase: ProjectService.OpenScrb start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: ProjectService.OpenScrb end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.OpenScrb()
}

// SaveScrb は ProjectServiceAPI を実装する。
func (_d ProjectServiceWithDebugLog) SaveScrb(workspaceID string, includeResults bool) (err error) {
	slog.Debug("usecase: ProjectService.SaveScrb start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: ProjectService.SaveScrb end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.SaveScrb(workspaceID, includeResults)
}

// SetApp は ProjectServiceAPI を実装する。
func (_d ProjectServiceWithDebugLog) SetApp(app *application.App) {
	slog.Debug("usecase: ProjectService.SetApp start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: ProjectService.SetApp end", slog.Duration("elapsed", elapsed))
	}()
	_d._base.SetApp(app)
	return
}
