// Code generated by gowrap. DO NOT EDIT.
// template: templates\slog_debug_slow.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package wails_service

//go:generate gowrap gen -p meguri-app/internal/usecase/wails_service -i ScraperServiceAPI -t templates\slog_debug_slow.gotmpl -o scraper_service_with_debug_log.go -v ServiceName=ScraperService -v DecoratorName=ScraperServiceWithDebugLog -l ""

import (
	"encoding/json"
	"log/slog"
	"meguri-app/internal/model"
	"time"

	"github.com/wailsapp/wails/v3/pkg/application"
)

// ScraperServiceWithDebugLog は ScraperServiceAPI に debug ログを付与するデコレータ。
type ScraperServiceWithDebugLog struct {
	_base ScraperServiceAPI
}

// NewScraperServiceWithDebugLog は base を debug ログ付きでラップする。
func NewScraperServiceWithDebugLog(base ScraperServiceAPI) ScraperServiceWithDebugLog {
	return ScraperServiceWithDebugLog{_base: base}
}

// FetchRobotsTxt は ScraperServiceAPI を実装する。
func (_d ScraperServiceWithDebugLog) FetchRobotsTxt(host string, baseURL string, appDefaults json.RawMessage, wsSettings json.RawMessage) (r1 model.RobotsTxtInfoDTO, err error) {
	slog.Debug("usecase: ScraperService.FetchRobotsTxt start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: ScraperService.FetchRobotsTxt end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.FetchRobotsTxt(host, baseURL, appDefaults, wsSettings)
}

// PauseCrawl は ScraperServiceAPI を実装する。
func (_d ScraperServiceWithDebugLog) PauseCrawl(runID string) (err error) {
	slog.Debug("usecase: ScraperService.PauseCrawl start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: ScraperService.PauseCrawl end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.PauseCrawl(runID)
}

// ResumeCrawl は ScraperServiceAPI を実装する。
func (_d ScraperServiceWithDebugLog) ResumeCrawl(runID string) (err error) {
	slog.Debug("usecase: ScraperService.ResumeCrawl start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: ScraperService.ResumeCrawl end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.ResumeCrawl(runID)
}

// ServiceShutdown は ScraperServiceAPI を実装する。
func (_d ScraperServiceWithDebugLog) ServiceShutdown() (err error) {
	slog.Debug("usecase: ScraperService.ServiceShutdown start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: ScraperService.ServiceShutdown end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.ServiceShutdown()
}

// SetApp は ScraperServiceAPI を実装する。
func (_d ScraperServiceWithDebugLog) SetApp(app *application.App) {
	slog.Debug("usecase: ScraperService.SetApp start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: ScraperService.SetApp end", slog.Duration("elapsed", elapsed))
	}()
	_d._base.SetApp(app)
	return
}

// StartCrawl は ScraperServiceAPI を実装する。
func (_d ScraperServiceWithDebugLog) StartCrawl(req model.StartCrawlRequest) (s1 string, err error) {
	slog.Debug("usecase: ScraperService.StartCrawl start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: ScraperService.StartCrawl end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.StartCrawl(req)
}

// StopCrawl は ScraperServiceAPI を実装する。
func (_d ScraperServiceWithDebugLog) StopCrawl(runID string) (err error) {
	slog.Debug("usecase: ScraperService.StopCrawl start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: ScraperService.StopCrawl end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.StopCrawl(runID)
}
