// Code generated by gowrap. DO NOT EDIT.
// template: templates\slog_debug_slow.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package wails_service

//go:generate gowrap gen -p meguri-app/internal/usecase/wails_service -i StoreServiceAPI -t templates\slog_debug_slow.gotmpl -o store_service_with_debug_log.go -v ServiceName=StoreService -v DecoratorName=StoreServiceWithDebugLog -l ""

import (
	"encoding/json"
	"log/slog"
	"meguri-app/internal/model"
	"time"

	"github.com/wailsapp/wails/v3/pkg/application"
)

// StoreServiceWithDebugLog は StoreServiceAPI に debug ログを付与するデコレータ。
type StoreServiceWithDebugLog struct {
	_base StoreServiceAPI
}

// NewStoreServiceWithDebugLog は base を debug ログ付きでラップする。
func NewStoreServiceWithDebugLog(base StoreServiceAPI) StoreServiceWithDebugLog {
	return StoreServiceWithDebugLog{_base: base}
}

// AppendNodeResult は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) AppendNodeResult(req model.AppendNodeResultRequest) (err error) {
	slog.Debug("usecase: StoreService.AppendNodeResult start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.AppendNodeResult end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.AppendNodeResult(req)
}

// BeginCrawlRun は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) BeginCrawlRun(req model.BeginCrawlRunRequest) (err error) {
	slog.Debug("usecase: StoreService.BeginCrawlRun start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.BeginCrawlRun end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.BeginCrawlRun(req)
}

// Bootstrap は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) Bootstrap() (err error) {
	slog.Debug("usecase: StoreService.Bootstrap start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.Bootstrap end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.Bootstrap()
}

// DeleteResults は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) DeleteResults(workspaceID string, nodeIDs []string) (err error) {
	slog.Debug("usecase: StoreService.DeleteResults start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.DeleteResults end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.DeleteResults(workspaceID, nodeIDs)
}

// DeleteWorkspace は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) DeleteWorkspace(id string) (err error) {
	slog.Debug("usecase: StoreService.DeleteWorkspace start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.DeleteWorkspace end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.DeleteWorkspace(id)
}

// DuplicateWorkspace は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) DuplicateWorkspace(req model.DuplicateWorkspaceRequest) (wp1 *model.WorkspaceDTO, err error) {
	slog.Debug("usecase: StoreService.DuplicateWorkspace start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.DuplicateWorkspace end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.DuplicateWorkspace(req)
}

// FinishCrawlRun は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) FinishCrawlRun(req model.FinishCrawlRunRequest) (err error) {
	slog.Debug("usecase: StoreService.FinishCrawlRun start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.FinishCrawlRun end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.FinishCrawlRun(req)
}

// GetAppDefaults は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) GetAppDefaults() (r1 json.RawMessage, err error) {
	slog.Debug("usecase: StoreService.GetAppDefaults start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.GetAppDefaults end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.GetAppDefaults()
}

// GetExportSession は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) GetExportSession() (e1 model.ExportSessionRequest, err error) {
	slog.Debug("usecase: StoreService.GetExportSession start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.GetExportSession end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.GetExportSession()
}

// GetGraphNodeStatuses は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) GetGraphNodeStatuses(workspaceID string, nodeIDs []string) (ga1 []model.GraphNodeStatusDTO, err error) {
	slog.Debug("usecase: StoreService.GetGraphNodeStatuses start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.GetGraphNodeStatuses end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.GetGraphNodeStatuses(workspaceID, nodeIDs)
}

// GetMaximizedNodeResult は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) GetMaximizedNodeResult() (m1 model.MaximizedNodeResultRequest, err error) {
	slog.Debug("usecase: StoreService.GetMaximizedNodeResult start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.GetMaximizedNodeResult end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.GetMaximizedNodeResult()
}

// GetNodeDiffDetail は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) GetNodeDiffDetail(workspaceID string, nodeID string) (n1 model.NodeDiffDetailDTO, err error) {
	slog.Debug("usecase: StoreService.GetNodeDiffDetail start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.GetNodeDiffDetail end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.GetNodeDiffDetail(workspaceID, nodeID)
}

// GetNodeDiffViewerSession は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) GetNodeDiffViewerSession() (n1 model.NodeDiffViewerRequest, err error) {
	slog.Debug("usecase: StoreService.GetNodeDiffViewerSession start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.GetNodeDiffViewerSession end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.GetNodeDiffViewerSession()
}

// GetNodeResult は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) GetNodeResult(workspaceID string, nodeID string) (cp1 *model.CrawlResultDTO, err error) {
	slog.Debug("usecase: StoreService.GetNodeResult start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.GetNodeResult end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.GetNodeResult(workspaceID, nodeID)
}

// GetNodeResults は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) GetNodeResults(workspaceID string, nodeIDs []string) (ca1 []model.CrawlResultDTO, err error) {
	slog.Debug("usecase: StoreService.GetNodeResults start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.GetNodeResults end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.GetNodeResults(workspaceID, nodeIDs)
}

// GetWorkspaceDiff は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) GetWorkspaceDiff(workspaceID string) (w1 model.WorkspaceDiffDTO, err error) {
	slog.Debug("usecase: StoreService.GetWorkspaceDiff start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.GetWorkspaceDiff end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.GetWorkspaceDiff(workspaceID)
}

// ListWorkspaces は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) ListWorkspaces() (wa1 []model.WorkspaceListItemDTO, err error) {
	slog.Debug("usecase: StoreService.ListWorkspaces start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.ListWorkspaces end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.ListWorkspaces()
}

// LoadWorkspace は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) LoadWorkspace(id string) (wp1 *model.WorkspaceDTO, err error) {
	slog.Debug("usecase: StoreService.LoadWorkspace start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.LoadWorkspace end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.LoadWorkspace(id)
}

// MergeResults は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) MergeResults(workspaceID string, nodeIDs []string, formats []string) (m1 model.MergeResultsResponseDTO, err error) {
	slog.Debug("usecase: StoreService.MergeResults start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.MergeResults end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.MergeResults(workspaceID, nodeIDs, formats)
}

// PatchGraphNodePositions は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) PatchGraphNodePositions(req model.PatchGraphNodePositionsRequest) (err error) {
	slog.Debug("usecase: StoreService.PatchGraphNodePositions start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.PatchGraphNodePositions end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.PatchGraphNodePositions(req)
}

// PatchGraphNodeStatus は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) PatchGraphNodeStatus(req model.PatchGraphNodeStatusRequest) (err error) {
	slog.Debug("usecase: StoreService.PatchGraphNodeStatus start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.PatchGraphNodeStatus end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.PatchGraphNodeStatus(req)
}

// SaveAppDefaults は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) SaveAppDefaults(config json.RawMessage) (s1 model.SaveSettingsResponseDTO, err error) {
	slog.Debug("usecase: StoreService.SaveAppDefaults start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.SaveAppDefaults end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.SaveAppDefaults(config)
}

// SaveExportFile は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) SaveExportFile(content string, defaultExt string) (err error) {
	slog.Debug("usecase: StoreService.SaveExportFile start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.SaveExportFile end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.SaveExportFile(content, defaultExt)
}

// SaveExportZip は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) SaveExportZip(entries []model.ExportZipEntryDTO, defaultExt string) (err error) {
	slog.Debug("usecase: StoreService.SaveExportZip start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.SaveExportZip end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.SaveExportZip(entries, defaultExt)
}

// SaveNodeSettings は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) SaveNodeSettings(workspaceID string, nodeID string, settings json.RawMessage) (s1 model.SaveSettingsResponseDTO, err error) {
	slog.Debug("usecase: StoreService.SaveNodeSettings start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.SaveNodeSettings end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.SaveNodeSettings(workspaceID, nodeID, settings)
}

// SaveResults は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) SaveResults(workspaceID string, nodeIDs []string) (err error) {
	slog.Debug("usecase: StoreService.SaveResults start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.SaveResults end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.SaveResults(workspaceID, nodeIDs)
}

// SaveResultsSnapshot は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) SaveResultsSnapshot(workspaceID string, runID string) (s1 string, err error) {
	slog.Debug("usecase: StoreService.SaveResultsSnapshot start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.SaveResultsSnapshot end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.SaveResultsSnapshot(workspaceID, runID)
}

// SaveWorkspace は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) SaveWorkspace(ws model.WorkspaceDTO) (err error) {
	slog.Debug("usecase: StoreService.SaveWorkspace start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.SaveWorkspace end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.SaveWorkspace(ws)
}

// SaveWorkspaceSettings は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) SaveWorkspaceSettings(workspaceID string, settings json.RawMessage) (s1 model.SaveSettingsResponseDTO, err error) {
	slog.Debug("usecase: StoreService.SaveWorkspaceSettings start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.SaveWorkspaceSettings end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.SaveWorkspaceSettings(workspaceID, settings)
}

// SetApp は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) SetApp(app *application.App) {
	slog.Debug("usecase: StoreService.SetApp start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.SetApp end", slog.Duration("elapsed", elapsed))
	}()
	_d._base.SetApp(app)
	return
}

// SetAppDefaults は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) SetAppDefaults(config json.RawMessage) (err error) {
	slog.Debug("usecase: StoreService.SetAppDefaults start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.SetAppDefaults end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.SetAppDefaults(config)
}

// ShowExportWindow は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) ShowExportWindow(req model.ExportSessionRequest) (err error) {
	slog.Debug("usecase: StoreService.ShowExportWindow start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.ShowExportWindow end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.ShowExportWindow(req)
}

// ShowMaximizedNodeResult は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) ShowMaximizedNodeResult(req model.MaximizedNodeResultRequest) (err error) {
	slog.Debug("usecase: StoreService.ShowMaximizedNodeResult start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.ShowMaximizedNodeResult end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.ShowMaximizedNodeResult(req)
}

// ShowNodeDiffWindow は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) ShowNodeDiffWindow(req model.NodeDiffViewerRequest) (err error) {
	slog.Debug("usecase: StoreService.ShowNodeDiffWindow start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.ShowNodeDiffWindow end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.ShowNodeDiffWindow(req)
}

// UpdateNodeResult は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) UpdateNodeResult(req model.UpdateNodeResultRequest) (cp1 *model.CrawlResultDTO, err error) {
	slog.Debug("usecase: StoreService.UpdateNodeResult start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.UpdateNodeResult end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.UpdateNodeResult(req)
}

// UpsertDiscoveredGraph は StoreServiceAPI を実装する。
func (_d StoreServiceWithDebugLog) UpsertDiscoveredGraph(req model.UpsertDiscoveredGraphRequest) (err error) {
	slog.Debug("usecase: StoreService.UpsertDiscoveredGraph start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: StoreService.UpsertDiscoveredGraph end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.UpsertDiscoveredGraph(req)
}
