// Code generated by gowrap. DO NOT EDIT.
// template: templates\slog_debug_slow.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package wails_service

//go:generate gowrap gen -p meguri-app/internal/usecase/wails_service -i UpdateServiceAPI -t templates\slog_debug_slow.gotmpl -o update_service_with_debug_log.go -v ServiceName=UpdateService -v DecoratorName=UpdateServiceWithDebugLog -l ""

import (
	"log/slog"
	"time"

	"github.com/wailsapp/wails/v3/pkg/application"
)

// UpdateServiceWithDebugLog は UpdateServiceAPI に debug ログを付与するデコレータ。
type UpdateServiceWithDebugLog struct {
	_base UpdateServiceAPI
}

// NewUpdateServiceWithDebugLog は base を debug ログ付きでラップする。
func NewUpdateServiceWithDebugLog(base UpdateServiceAPI) UpdateServiceWithDebugLog {
	return UpdateServiceWithDebugLog{_base: base}
}

// ApplyUpdate は UpdateServiceAPI を実装する。
func (_d UpdateServiceWithDebugLog) ApplyUpdate() (err error) {
	slog.Debug("usecase: UpdateService.ApplyUpdate start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: UpdateService.ApplyUpdate end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.ApplyUpdate()
}

// Check は UpdateServiceAPI を実装する。
func (_d UpdateServiceWithDebugLog) Check() (u1 UpdateStatus, err error) {
	slog.Debug("usecase: UpdateService.Check start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: UpdateService.Check end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.Check()
}

// CheckForUpdates は UpdateServiceAPI を実装する。
func (_d UpdateServiceWithDebugLog) CheckForUpdates() (c1 CheckForUpdatesResult, err error) {
	slog.Debug("usecase: UpdateService.CheckForUpdates start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: UpdateService.CheckForUpdates end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.CheckForUpdates()
}

// CheckOnStartup は UpdateServiceAPI を実装する。
func (_d UpdateServiceWithDebugLog) CheckOnStartup() {
	slog.Debug("usecase: UpdateService.CheckOnStartup start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: UpdateService.CheckOnStartup end", slog.Duration("elapsed", elapsed))
	}()
	_d._base.CheckOnStartup()
	return
}

// GetStatus は UpdateServiceAPI を実装する。
func (_d UpdateServiceWithDebugLog) GetStatus() (u1 UpdateStatus, err error) {
	slog.Debug("usecase: UpdateService.GetStatus start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: UpdateService.GetStatus end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.GetStatus()
}

// GetUpdatePromptSnapshot は UpdateServiceAPI を実装する。
func (_d UpdateServiceWithDebugLog) GetUpdatePromptSnapshot() (u1 UpdatePromptSnapshot, err error) {
	slog.Debug("usecase: UpdateService.GetUpdatePromptSnapshot start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: UpdateService.GetUpdatePromptSnapshot end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.GetUpdatePromptSnapshot()
}

// PromptUpdate は UpdateServiceAPI を実装する。
func (_d UpdateServiceWithDebugLog) PromptUpdate() (u1 UpdatePromptResult, err error) {
	slog.Debug("usecase: UpdateService.PromptUpdate start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: UpdateService.PromptUpdate end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.PromptUpdate()
}

// SetApp は UpdateServiceAPI を実装する。
func (_d UpdateServiceWithDebugLog) SetApp(app *application.App) {
	slog.Debug("usecase: UpdateService.SetApp start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: UpdateService.SetApp end", slog.Duration("elapsed", elapsed))
	}()
	_d._base.SetApp(app)
	return
}

// StartPeriodicCheck は UpdateServiceAPI を実装する。
func (_d UpdateServiceWithDebugLog) StartPeriodicCheck(interval time.Duration) {
	slog.Debug("usecase: UpdateService.StartPeriodicCheck start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: UpdateService.StartPeriodicCheck end", slog.Duration("elapsed", elapsed))
	}()
	_d._base.StartPeriodicCheck(interval)
	return
}

// SubmitUpdatePrompt は UpdateServiceAPI を実装する。
func (_d UpdateServiceWithDebugLog) SubmitUpdatePrompt(action string) (err error) {
	slog.Debug("usecase: UpdateService.SubmitUpdatePrompt start")
	start := time.Now()
	defer func() {
		elapsed := time.Since(start)
		if elapsed < debugLogSlowThreshold {
			return
		}
		slog.Debug("usecase: UpdateService.SubmitUpdatePrompt end", slog.Duration("elapsed", elapsed))
	}()
	return _d._base.SubmitUpdatePrompt(action)
}
