// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ScraperService は backend crawler を駆動し Wails Event で進捗を配信する。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";

/**
 * PauseCrawl は実行中 crawl を一時停止する。
 */
export function PauseCrawl(runID: string): $CancellablePromise<void> {
    return $Call.ByID(1703968671, runID);
}

/**
 * ResumeCrawl は一時停止中 crawl を再開する。
 */
export function ResumeCrawl(runID: string): $CancellablePromise<void> {
    return $Call.ByID(2904454848, runID);
}

/**
 * SetApp は Wails App を後から注入する（Event 発火用）。
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(1906917273, app);
}

/**
 * StartCrawl はクロールを非同期で開始する。
 */
export function StartCrawl(req: model$0.StartCrawlRequest): $CancellablePromise<void> {
    return $Call.ByID(1172127101, req);
}

/**
 * StopCrawl は実行中 crawl をキャンセルする。
 */
export function StopCrawl(runID: string): $CancellablePromise<void> {
    return $Call.ByID(126324029, runID);
}
