// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StoreService は Wails 公開 Store RPC。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";

/**
 * AppendNodeResult はノード結果行を追加する。
 */
export function AppendNodeResult(req: model$0.AppendNodeResultRequest): $CancellablePromise<void> {
    return $Call.ByID(3510917024, req);
}

/**
 * BeginCrawlRun は crawl run を開始する。
 */
export function BeginCrawlRun(req: model$0.BeginCrawlRunRequest): $CancellablePromise<void> {
    return $Call.ByID(908078694, req);
}

/**
 * Bootstrap は起動時 DB 初期化。
 */
export function Bootstrap(): $CancellablePromise<void> {
    return $Call.ByID(1505416513);
}

/**
 * DeleteResults は最新結果を削除する。
 */
export function DeleteResults(workspaceID: string, nodeIDs: string[]): $CancellablePromise<void> {
    return $Call.ByID(914537352, workspaceID, nodeIDs);
}

/**
 * DuplicateWorkspace は WS を複製する。
 */
export function DuplicateWorkspace(id: string): $CancellablePromise<model$0.WorkspaceDTO | null> {
    return $Call.ByID(2954192207, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * FinishCrawlRun は crawl run を終了する。
 */
export function FinishCrawlRun(req: model$0.FinishCrawlRunRequest): $CancellablePromise<void> {
    return $Call.ByID(72160794, req);
}

/**
 * GetAppDefaults はアプリ既定設定を返す。
 */
export function GetAppDefaults(): $CancellablePromise<json$0.RawMessage> {
    return $Call.ByID(986519116);
}

/**
 * GetNodeResult はノード結果を返す。
 */
export function GetNodeResult(workspaceID: string, nodeID: string): $CancellablePromise<model$0.CrawlResultDTO | null> {
    return $Call.ByID(2230381414, workspaceID, nodeID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetNodeResults は複数ノード結果を返す。
 */
export function GetNodeResults(workspaceID: string, nodeIDs: string[]): $CancellablePromise<model$0.CrawlResultDTO[]> {
    return $Call.ByID(1547833871, workspaceID, nodeIDs).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetWorkspaceDiff は WS 差分を返す。
 */
export function GetWorkspaceDiff(workspaceID: string): $CancellablePromise<model$0.WorkspaceDiffDTO> {
    return $Call.ByID(962553539, workspaceID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ListWorkspaces は WS 一覧を返す。
 */
export function ListWorkspaces(): $CancellablePromise<model$0.WorkspaceListItemDTO[]> {
    return $Call.ByID(2887877563).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * LoadWorkspace は WS を読み込む。
 */
export function LoadWorkspace(id: string): $CancellablePromise<model$0.WorkspaceDTO | null> {
    return $Call.ByID(1251890114, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * MergeResults は結果をマージする。
 */
export function MergeResults(workspaceID: string, nodeIDs: string[], formats: string[]): $CancellablePromise<model$0.MergeResultsResponseDTO> {
    return $Call.ByID(1725193583, workspaceID, nodeIDs, formats).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * PatchGraphNodeStatus はノード status を更新する。
 */
export function PatchGraphNodeStatus(req: model$0.PatchGraphNodeStatusRequest): $CancellablePromise<void> {
    return $Call.ByID(1748401541, req);
}

/**
 * SaveAppDefaults はアプリ既定設定を保存する。
 */
export function SaveAppDefaults(config: json$0.RawMessage): $CancellablePromise<model$0.SaveSettingsResponseDTO> {
    return $Call.ByID(3060042429, config).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * SaveDomainSettings はドメイン設定を保存する。
 */
export function SaveDomainSettings(workspaceID: string, host: string, settings: json$0.RawMessage): $CancellablePromise<model$0.SaveSettingsResponseDTO> {
    return $Call.ByID(319574929, workspaceID, host, settings).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * SaveNodeSettings はノード設定を保存する。
 */
export function SaveNodeSettings(workspaceID: string, nodeID: string, settings: json$0.RawMessage): $CancellablePromise<model$0.SaveSettingsResponseDTO> {
    return $Call.ByID(3533873137, workspaceID, nodeID, settings).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * SaveResults は baseline 用に結果を保存する。
 */
export function SaveResults(workspaceID: string, nodeIDs: string[]): $CancellablePromise<void> {
    return $Call.ByID(965942430, workspaceID, nodeIDs);
}

/**
 * SaveResultsSnapshot は baseline snapshot を保存する。
 */
export function SaveResultsSnapshot(workspaceID: string, runID: string): $CancellablePromise<string> {
    return $Call.ByID(1866471234, workspaceID, runID);
}

/**
 * SaveWorkspace は WS を保存する。
 */
export function SaveWorkspace(ws: model$0.WorkspaceDTO): $CancellablePromise<void> {
    return $Call.ByID(3619559933, ws);
}

/**
 * SaveWorkspaceSettings は WS 設定を保存する。
 */
export function SaveWorkspaceSettings(workspaceID: string, settings: json$0.RawMessage): $CancellablePromise<model$0.SaveSettingsResponseDTO> {
    return $Call.ByID(2942997632, workspaceID, settings).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * SetAppDefaults はアプリ既定設定を設定する。
 */
export function SetAppDefaults(config: json$0.RawMessage): $CancellablePromise<void> {
    return $Call.ByID(3135309632, config);
}

/**
 * UpsertDiscoveredGraph は crawl 中に発見したノードとエッジを永続化する。
 */
export function UpsertDiscoveredGraph(req: model$0.UpsertDiscoveredGraphRequest): $CancellablePromise<void> {
    return $Call.ByID(617689704, req);
}

// Private type creation functions
const $$createType0 = model$0.WorkspaceDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.CrawlResultDTO.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType2);
const $$createType5 = model$0.WorkspaceDiffDTO.createFrom;
const $$createType6 = model$0.WorkspaceListItemDTO.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = model$0.MergeResultsResponseDTO.createFrom;
const $$createType9 = model$0.SaveSettingsResponseDTO.createFrom;
