// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"meguri-app/internal/model"
)

func newCrawlRun(db *gorm.DB, opts ...gen.DOOption) crawlRun {
	_crawlRun := crawlRun{}

	_crawlRun.crawlRunDo.UseDB(db, opts...)
	_crawlRun.crawlRunDo.UseModel(&model.CrawlRun{})

	tableName := _crawlRun.crawlRunDo.TableName()
	_crawlRun.ALL = field.NewAsterisk(tableName)
	_crawlRun.ID = field.NewString(tableName, "id")
	_crawlRun.WorkspaceID = field.NewString(tableName, "workspace_id")
	_crawlRun.Mode = field.NewInt32(tableName, "mode")
	_crawlRun.Status = field.NewString(tableName, "status")
	_crawlRun.StartedAt = field.NewString(tableName, "started_at")
	_crawlRun.FinishedAt = field.NewString(tableName, "finished_at")
	_crawlRun.SummaryJSON = field.NewString(tableName, "summary_json")
	_crawlRun.ErrorMessage = field.NewString(tableName, "error_message")

	_crawlRun.fillFieldMap()

	return _crawlRun
}

type crawlRun struct {
	crawlRunDo crawlRunDo

	ALL          field.Asterisk
	ID           field.String
	WorkspaceID  field.String
	Mode         field.Int32
	Status       field.String
	StartedAt    field.String
	FinishedAt   field.String
	SummaryJSON  field.String
	ErrorMessage field.String

	fieldMap map[string]field.Expr
}

func (c crawlRun) Table(newTableName string) *crawlRun {
	c.crawlRunDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c crawlRun) As(alias string) *crawlRun {
	c.crawlRunDo.DO = *(c.crawlRunDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *crawlRun) updateTableName(table string) *crawlRun {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewString(table, "id")
	c.WorkspaceID = field.NewString(table, "workspace_id")
	c.Mode = field.NewInt32(table, "mode")
	c.Status = field.NewString(table, "status")
	c.StartedAt = field.NewString(table, "started_at")
	c.FinishedAt = field.NewString(table, "finished_at")
	c.SummaryJSON = field.NewString(table, "summary_json")
	c.ErrorMessage = field.NewString(table, "error_message")

	c.fillFieldMap()

	return c
}

func (c *crawlRun) WithContext(ctx context.Context) ICrawlRunDo { return c.crawlRunDo.WithContext(ctx) }

func (c crawlRun) TableName() string { return c.crawlRunDo.TableName() }

func (c crawlRun) Alias() string { return c.crawlRunDo.Alias() }

func (c crawlRun) Columns(cols ...field.Expr) gen.Columns { return c.crawlRunDo.Columns(cols...) }

func (c *crawlRun) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *crawlRun) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 8)
	c.fieldMap["id"] = c.ID
	c.fieldMap["workspace_id"] = c.WorkspaceID
	c.fieldMap["mode"] = c.Mode
	c.fieldMap["status"] = c.Status
	c.fieldMap["started_at"] = c.StartedAt
	c.fieldMap["finished_at"] = c.FinishedAt
	c.fieldMap["summary_json"] = c.SummaryJSON
	c.fieldMap["error_message"] = c.ErrorMessage
}

func (c crawlRun) clone(db *gorm.DB) crawlRun {
	c.crawlRunDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c crawlRun) replaceDB(db *gorm.DB) crawlRun {
	c.crawlRunDo.ReplaceDB(db)
	return c
}

type crawlRunDo struct{ gen.DO }

type ICrawlRunDo interface {
	gen.SubQuery
	Debug() ICrawlRunDo
	WithContext(ctx context.Context) ICrawlRunDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICrawlRunDo
	WriteDB() ICrawlRunDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICrawlRunDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICrawlRunDo
	Not(conds ...gen.Condition) ICrawlRunDo
	Or(conds ...gen.Condition) ICrawlRunDo
	Select(conds ...field.Expr) ICrawlRunDo
	Where(conds ...gen.Condition) ICrawlRunDo
	Order(conds ...field.Expr) ICrawlRunDo
	Distinct(cols ...field.Expr) ICrawlRunDo
	Omit(cols ...field.Expr) ICrawlRunDo
	Join(table schema.Tabler, on ...field.Expr) ICrawlRunDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICrawlRunDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICrawlRunDo
	Group(cols ...field.Expr) ICrawlRunDo
	Having(conds ...gen.Condition) ICrawlRunDo
	Limit(limit int) ICrawlRunDo
	Offset(offset int) ICrawlRunDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICrawlRunDo
	Unscoped() ICrawlRunDo
	Create(values ...*model.CrawlRun) error
	CreateInBatches(values []*model.CrawlRun, batchSize int) error
	Save(values ...*model.CrawlRun) error
	First() (*model.CrawlRun, error)
	Take() (*model.CrawlRun, error)
	Last() (*model.CrawlRun, error)
	Find() ([]*model.CrawlRun, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CrawlRun, err error)
	FindInBatches(result *[]*model.CrawlRun, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CrawlRun) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICrawlRunDo
	Assign(attrs ...field.AssignExpr) ICrawlRunDo
	Joins(fields ...field.RelationField) ICrawlRunDo
	Preload(fields ...field.RelationField) ICrawlRunDo
	FirstOrInit() (*model.CrawlRun, error)
	FirstOrCreate() (*model.CrawlRun, error)
	FindByPage(offset int, limit int) (result []*model.CrawlRun, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICrawlRunDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c crawlRunDo) Debug() ICrawlRunDo {
	return c.withDO(c.DO.Debug())
}

func (c crawlRunDo) WithContext(ctx context.Context) ICrawlRunDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c crawlRunDo) ReadDB() ICrawlRunDo {
	return c.Clauses(dbresolver.Read)
}

func (c crawlRunDo) WriteDB() ICrawlRunDo {
	return c.Clauses(dbresolver.Write)
}

func (c crawlRunDo) Session(config *gorm.Session) ICrawlRunDo {
	return c.withDO(c.DO.Session(config))
}

func (c crawlRunDo) Clauses(conds ...clause.Expression) ICrawlRunDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c crawlRunDo) Returning(value interface{}, columns ...string) ICrawlRunDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c crawlRunDo) Not(conds ...gen.Condition) ICrawlRunDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c crawlRunDo) Or(conds ...gen.Condition) ICrawlRunDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c crawlRunDo) Select(conds ...field.Expr) ICrawlRunDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c crawlRunDo) Where(conds ...gen.Condition) ICrawlRunDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c crawlRunDo) Order(conds ...field.Expr) ICrawlRunDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c crawlRunDo) Distinct(cols ...field.Expr) ICrawlRunDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c crawlRunDo) Omit(cols ...field.Expr) ICrawlRunDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c crawlRunDo) Join(table schema.Tabler, on ...field.Expr) ICrawlRunDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c crawlRunDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICrawlRunDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c crawlRunDo) RightJoin(table schema.Tabler, on ...field.Expr) ICrawlRunDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c crawlRunDo) Group(cols ...field.Expr) ICrawlRunDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c crawlRunDo) Having(conds ...gen.Condition) ICrawlRunDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c crawlRunDo) Limit(limit int) ICrawlRunDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c crawlRunDo) Offset(offset int) ICrawlRunDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c crawlRunDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICrawlRunDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c crawlRunDo) Unscoped() ICrawlRunDo {
	return c.withDO(c.DO.Unscoped())
}

func (c crawlRunDo) Create(values ...*model.CrawlRun) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c crawlRunDo) CreateInBatches(values []*model.CrawlRun, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c crawlRunDo) Save(values ...*model.CrawlRun) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c crawlRunDo) First() (*model.CrawlRun, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CrawlRun), nil
	}
}

func (c crawlRunDo) Take() (*model.CrawlRun, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CrawlRun), nil
	}
}

func (c crawlRunDo) Last() (*model.CrawlRun, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CrawlRun), nil
	}
}

func (c crawlRunDo) Find() ([]*model.CrawlRun, error) {
	result, err := c.DO.Find()
	return result.([]*model.CrawlRun), err
}

func (c crawlRunDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CrawlRun, err error) {
	buf := make([]*model.CrawlRun, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c crawlRunDo) FindInBatches(result *[]*model.CrawlRun, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c crawlRunDo) Attrs(attrs ...field.AssignExpr) ICrawlRunDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c crawlRunDo) Assign(attrs ...field.AssignExpr) ICrawlRunDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c crawlRunDo) Joins(fields ...field.RelationField) ICrawlRunDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c crawlRunDo) Preload(fields ...field.RelationField) ICrawlRunDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c crawlRunDo) FirstOrInit() (*model.CrawlRun, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CrawlRun), nil
	}
}

func (c crawlRunDo) FirstOrCreate() (*model.CrawlRun, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CrawlRun), nil
	}
}

func (c crawlRunDo) FindByPage(offset int, limit int) (result []*model.CrawlRun, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c crawlRunDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c crawlRunDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c crawlRunDo) Delete(models ...*model.CrawlRun) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *crawlRunDo) withDO(do gen.Dao) *crawlRunDo {
	c.DO = *do.(*gen.DO)
	return c
}
