// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"scraperbot-front/internal/model"
)

func newDomainSetting(db *gorm.DB, opts ...gen.DOOption) domainSetting {
	_domainSetting := domainSetting{}

	_domainSetting.domainSettingDo.UseDB(db, opts...)
	_domainSetting.domainSettingDo.UseModel(&model.DomainSetting{})

	tableName := _domainSetting.domainSettingDo.TableName()
	_domainSetting.ALL = field.NewAsterisk(tableName)
	_domainSetting.WorkspaceID = field.NewString(tableName, "workspace_id")
	_domainSetting.Host = field.NewString(tableName, "host")
	_domainSetting.SettingsJSON = field.NewString(tableName, "settings_json")

	_domainSetting.fillFieldMap()

	return _domainSetting
}

type domainSetting struct {
	domainSettingDo domainSettingDo

	ALL          field.Asterisk
	WorkspaceID  field.String
	Host         field.String
	SettingsJSON field.String

	fieldMap map[string]field.Expr
}

func (d domainSetting) Table(newTableName string) *domainSetting {
	d.domainSettingDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d domainSetting) As(alias string) *domainSetting {
	d.domainSettingDo.DO = *(d.domainSettingDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *domainSetting) updateTableName(table string) *domainSetting {
	d.ALL = field.NewAsterisk(table)
	d.WorkspaceID = field.NewString(table, "workspace_id")
	d.Host = field.NewString(table, "host")
	d.SettingsJSON = field.NewString(table, "settings_json")

	d.fillFieldMap()

	return d
}

func (d *domainSetting) WithContext(ctx context.Context) IDomainSettingDo {
	return d.domainSettingDo.WithContext(ctx)
}

func (d domainSetting) TableName() string { return d.domainSettingDo.TableName() }

func (d domainSetting) Alias() string { return d.domainSettingDo.Alias() }

func (d domainSetting) Columns(cols ...field.Expr) gen.Columns {
	return d.domainSettingDo.Columns(cols...)
}

func (d *domainSetting) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *domainSetting) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 3)
	d.fieldMap["workspace_id"] = d.WorkspaceID
	d.fieldMap["host"] = d.Host
	d.fieldMap["settings_json"] = d.SettingsJSON
}

func (d domainSetting) clone(db *gorm.DB) domainSetting {
	d.domainSettingDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d domainSetting) replaceDB(db *gorm.DB) domainSetting {
	d.domainSettingDo.ReplaceDB(db)
	return d
}

type domainSettingDo struct{ gen.DO }

type IDomainSettingDo interface {
	gen.SubQuery
	Debug() IDomainSettingDo
	WithContext(ctx context.Context) IDomainSettingDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDomainSettingDo
	WriteDB() IDomainSettingDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDomainSettingDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDomainSettingDo
	Not(conds ...gen.Condition) IDomainSettingDo
	Or(conds ...gen.Condition) IDomainSettingDo
	Select(conds ...field.Expr) IDomainSettingDo
	Where(conds ...gen.Condition) IDomainSettingDo
	Order(conds ...field.Expr) IDomainSettingDo
	Distinct(cols ...field.Expr) IDomainSettingDo
	Omit(cols ...field.Expr) IDomainSettingDo
	Join(table schema.Tabler, on ...field.Expr) IDomainSettingDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDomainSettingDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDomainSettingDo
	Group(cols ...field.Expr) IDomainSettingDo
	Having(conds ...gen.Condition) IDomainSettingDo
	Limit(limit int) IDomainSettingDo
	Offset(offset int) IDomainSettingDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDomainSettingDo
	Unscoped() IDomainSettingDo
	Create(values ...*model.DomainSetting) error
	CreateInBatches(values []*model.DomainSetting, batchSize int) error
	Save(values ...*model.DomainSetting) error
	First() (*model.DomainSetting, error)
	Take() (*model.DomainSetting, error)
	Last() (*model.DomainSetting, error)
	Find() ([]*model.DomainSetting, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DomainSetting, err error)
	FindInBatches(result *[]*model.DomainSetting, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DomainSetting) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDomainSettingDo
	Assign(attrs ...field.AssignExpr) IDomainSettingDo
	Joins(fields ...field.RelationField) IDomainSettingDo
	Preload(fields ...field.RelationField) IDomainSettingDo
	FirstOrInit() (*model.DomainSetting, error)
	FirstOrCreate() (*model.DomainSetting, error)
	FindByPage(offset int, limit int) (result []*model.DomainSetting, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDomainSettingDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d domainSettingDo) Debug() IDomainSettingDo {
	return d.withDO(d.DO.Debug())
}

func (d domainSettingDo) WithContext(ctx context.Context) IDomainSettingDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d domainSettingDo) ReadDB() IDomainSettingDo {
	return d.Clauses(dbresolver.Read)
}

func (d domainSettingDo) WriteDB() IDomainSettingDo {
	return d.Clauses(dbresolver.Write)
}

func (d domainSettingDo) Session(config *gorm.Session) IDomainSettingDo {
	return d.withDO(d.DO.Session(config))
}

func (d domainSettingDo) Clauses(conds ...clause.Expression) IDomainSettingDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d domainSettingDo) Returning(value interface{}, columns ...string) IDomainSettingDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d domainSettingDo) Not(conds ...gen.Condition) IDomainSettingDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d domainSettingDo) Or(conds ...gen.Condition) IDomainSettingDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d domainSettingDo) Select(conds ...field.Expr) IDomainSettingDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d domainSettingDo) Where(conds ...gen.Condition) IDomainSettingDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d domainSettingDo) Order(conds ...field.Expr) IDomainSettingDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d domainSettingDo) Distinct(cols ...field.Expr) IDomainSettingDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d domainSettingDo) Omit(cols ...field.Expr) IDomainSettingDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d domainSettingDo) Join(table schema.Tabler, on ...field.Expr) IDomainSettingDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d domainSettingDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDomainSettingDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d domainSettingDo) RightJoin(table schema.Tabler, on ...field.Expr) IDomainSettingDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d domainSettingDo) Group(cols ...field.Expr) IDomainSettingDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d domainSettingDo) Having(conds ...gen.Condition) IDomainSettingDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d domainSettingDo) Limit(limit int) IDomainSettingDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d domainSettingDo) Offset(offset int) IDomainSettingDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d domainSettingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDomainSettingDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d domainSettingDo) Unscoped() IDomainSettingDo {
	return d.withDO(d.DO.Unscoped())
}

func (d domainSettingDo) Create(values ...*model.DomainSetting) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d domainSettingDo) CreateInBatches(values []*model.DomainSetting, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d domainSettingDo) Save(values ...*model.DomainSetting) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d domainSettingDo) First() (*model.DomainSetting, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DomainSetting), nil
	}
}

func (d domainSettingDo) Take() (*model.DomainSetting, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DomainSetting), nil
	}
}

func (d domainSettingDo) Last() (*model.DomainSetting, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DomainSetting), nil
	}
}

func (d domainSettingDo) Find() ([]*model.DomainSetting, error) {
	result, err := d.DO.Find()
	return result.([]*model.DomainSetting), err
}

func (d domainSettingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DomainSetting, err error) {
	buf := make([]*model.DomainSetting, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d domainSettingDo) FindInBatches(result *[]*model.DomainSetting, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d domainSettingDo) Attrs(attrs ...field.AssignExpr) IDomainSettingDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d domainSettingDo) Assign(attrs ...field.AssignExpr) IDomainSettingDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d domainSettingDo) Joins(fields ...field.RelationField) IDomainSettingDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d domainSettingDo) Preload(fields ...field.RelationField) IDomainSettingDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d domainSettingDo) FirstOrInit() (*model.DomainSetting, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DomainSetting), nil
	}
}

func (d domainSettingDo) FirstOrCreate() (*model.DomainSetting, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DomainSetting), nil
	}
}

func (d domainSettingDo) FindByPage(offset int, limit int) (result []*model.DomainSetting, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d domainSettingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d domainSettingDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d domainSettingDo) Delete(models ...*model.DomainSetting) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *domainSettingDo) withDO(do gen.Dao) *domainSettingDo {
	d.DO = *do.(*gen.DO)
	return d
}
