// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q            = new(Query)
	AppConfig    *appConfig
	CrawlRun     *crawlRun
	GraphEdge    *graphEdge
	GraphNode    *graphNode
	GraphUIState *graphUIState
	NodeResult   *nodeResult
	Workspace    *workspace
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AppConfig = &Q.AppConfig
	CrawlRun = &Q.CrawlRun
	GraphEdge = &Q.GraphEdge
	GraphNode = &Q.GraphNode
	GraphUIState = &Q.GraphUIState
	NodeResult = &Q.NodeResult
	Workspace = &Q.Workspace
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:           db,
		AppConfig:    newAppConfig(db, opts...),
		CrawlRun:     newCrawlRun(db, opts...),
		GraphEdge:    newGraphEdge(db, opts...),
		GraphNode:    newGraphNode(db, opts...),
		GraphUIState: newGraphUIState(db, opts...),
		NodeResult:   newNodeResult(db, opts...),
		Workspace:    newWorkspace(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AppConfig    appConfig
	CrawlRun     crawlRun
	GraphEdge    graphEdge
	GraphNode    graphNode
	GraphUIState graphUIState
	NodeResult   nodeResult
	Workspace    workspace
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		AppConfig:    q.AppConfig.clone(db),
		CrawlRun:     q.CrawlRun.clone(db),
		GraphEdge:    q.GraphEdge.clone(db),
		GraphNode:    q.GraphNode.clone(db),
		GraphUIState: q.GraphUIState.clone(db),
		NodeResult:   q.NodeResult.clone(db),
		Workspace:    q.Workspace.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		AppConfig:    q.AppConfig.replaceDB(db),
		CrawlRun:     q.CrawlRun.replaceDB(db),
		GraphEdge:    q.GraphEdge.replaceDB(db),
		GraphNode:    q.GraphNode.replaceDB(db),
		GraphUIState: q.GraphUIState.replaceDB(db),
		NodeResult:   q.NodeResult.replaceDB(db),
		Workspace:    q.Workspace.replaceDB(db),
	}
}

type queryCtx struct {
	AppConfig    IAppConfigDo
	CrawlRun     ICrawlRunDo
	GraphEdge    IGraphEdgeDo
	GraphNode    IGraphNodeDo
	GraphUIState IGraphUIStateDo
	NodeResult   INodeResultDo
	Workspace    IWorkspaceDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AppConfig:    q.AppConfig.WithContext(ctx),
		CrawlRun:     q.CrawlRun.WithContext(ctx),
		GraphEdge:    q.GraphEdge.WithContext(ctx),
		GraphNode:    q.GraphNode.WithContext(ctx),
		GraphUIState: q.GraphUIState.WithContext(ctx),
		NodeResult:   q.NodeResult.WithContext(ctx),
		Workspace:    q.Workspace.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
