// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"scraperbot-front/internal/model"
)

func newGraphEdge(db *gorm.DB, opts ...gen.DOOption) graphEdge {
	_graphEdge := graphEdge{}

	_graphEdge.graphEdgeDo.UseDB(db, opts...)
	_graphEdge.graphEdgeDo.UseModel(&model.GraphEdge{})

	tableName := _graphEdge.graphEdgeDo.TableName()
	_graphEdge.ALL = field.NewAsterisk(tableName)
	_graphEdge.WorkspaceID = field.NewString(tableName, "workspace_id")
	_graphEdge.ID = field.NewString(tableName, "id")
	_graphEdge.SourceNodeID = field.NewString(tableName, "source_node_id")
	_graphEdge.TargetNodeID = field.NewString(tableName, "target_node_id")

	_graphEdge.fillFieldMap()

	return _graphEdge
}

type graphEdge struct {
	graphEdgeDo graphEdgeDo

	ALL          field.Asterisk
	WorkspaceID  field.String
	ID           field.String
	SourceNodeID field.String
	TargetNodeID field.String

	fieldMap map[string]field.Expr
}

func (g graphEdge) Table(newTableName string) *graphEdge {
	g.graphEdgeDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g graphEdge) As(alias string) *graphEdge {
	g.graphEdgeDo.DO = *(g.graphEdgeDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *graphEdge) updateTableName(table string) *graphEdge {
	g.ALL = field.NewAsterisk(table)
	g.WorkspaceID = field.NewString(table, "workspace_id")
	g.ID = field.NewString(table, "id")
	g.SourceNodeID = field.NewString(table, "source_node_id")
	g.TargetNodeID = field.NewString(table, "target_node_id")

	g.fillFieldMap()

	return g
}

func (g *graphEdge) WithContext(ctx context.Context) IGraphEdgeDo {
	return g.graphEdgeDo.WithContext(ctx)
}

func (g graphEdge) TableName() string { return g.graphEdgeDo.TableName() }

func (g graphEdge) Alias() string { return g.graphEdgeDo.Alias() }

func (g graphEdge) Columns(cols ...field.Expr) gen.Columns { return g.graphEdgeDo.Columns(cols...) }

func (g *graphEdge) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *graphEdge) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 4)
	g.fieldMap["workspace_id"] = g.WorkspaceID
	g.fieldMap["id"] = g.ID
	g.fieldMap["source_node_id"] = g.SourceNodeID
	g.fieldMap["target_node_id"] = g.TargetNodeID
}

func (g graphEdge) clone(db *gorm.DB) graphEdge {
	g.graphEdgeDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g graphEdge) replaceDB(db *gorm.DB) graphEdge {
	g.graphEdgeDo.ReplaceDB(db)
	return g
}

type graphEdgeDo struct{ gen.DO }

type IGraphEdgeDo interface {
	gen.SubQuery
	Debug() IGraphEdgeDo
	WithContext(ctx context.Context) IGraphEdgeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGraphEdgeDo
	WriteDB() IGraphEdgeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGraphEdgeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGraphEdgeDo
	Not(conds ...gen.Condition) IGraphEdgeDo
	Or(conds ...gen.Condition) IGraphEdgeDo
	Select(conds ...field.Expr) IGraphEdgeDo
	Where(conds ...gen.Condition) IGraphEdgeDo
	Order(conds ...field.Expr) IGraphEdgeDo
	Distinct(cols ...field.Expr) IGraphEdgeDo
	Omit(cols ...field.Expr) IGraphEdgeDo
	Join(table schema.Tabler, on ...field.Expr) IGraphEdgeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGraphEdgeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGraphEdgeDo
	Group(cols ...field.Expr) IGraphEdgeDo
	Having(conds ...gen.Condition) IGraphEdgeDo
	Limit(limit int) IGraphEdgeDo
	Offset(offset int) IGraphEdgeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGraphEdgeDo
	Unscoped() IGraphEdgeDo
	Create(values ...*model.GraphEdge) error
	CreateInBatches(values []*model.GraphEdge, batchSize int) error
	Save(values ...*model.GraphEdge) error
	First() (*model.GraphEdge, error)
	Take() (*model.GraphEdge, error)
	Last() (*model.GraphEdge, error)
	Find() ([]*model.GraphEdge, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GraphEdge, err error)
	FindInBatches(result *[]*model.GraphEdge, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.GraphEdge) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGraphEdgeDo
	Assign(attrs ...field.AssignExpr) IGraphEdgeDo
	Joins(fields ...field.RelationField) IGraphEdgeDo
	Preload(fields ...field.RelationField) IGraphEdgeDo
	FirstOrInit() (*model.GraphEdge, error)
	FirstOrCreate() (*model.GraphEdge, error)
	FindByPage(offset int, limit int) (result []*model.GraphEdge, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGraphEdgeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g graphEdgeDo) Debug() IGraphEdgeDo {
	return g.withDO(g.DO.Debug())
}

func (g graphEdgeDo) WithContext(ctx context.Context) IGraphEdgeDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g graphEdgeDo) ReadDB() IGraphEdgeDo {
	return g.Clauses(dbresolver.Read)
}

func (g graphEdgeDo) WriteDB() IGraphEdgeDo {
	return g.Clauses(dbresolver.Write)
}

func (g graphEdgeDo) Session(config *gorm.Session) IGraphEdgeDo {
	return g.withDO(g.DO.Session(config))
}

func (g graphEdgeDo) Clauses(conds ...clause.Expression) IGraphEdgeDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g graphEdgeDo) Returning(value interface{}, columns ...string) IGraphEdgeDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g graphEdgeDo) Not(conds ...gen.Condition) IGraphEdgeDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g graphEdgeDo) Or(conds ...gen.Condition) IGraphEdgeDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g graphEdgeDo) Select(conds ...field.Expr) IGraphEdgeDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g graphEdgeDo) Where(conds ...gen.Condition) IGraphEdgeDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g graphEdgeDo) Order(conds ...field.Expr) IGraphEdgeDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g graphEdgeDo) Distinct(cols ...field.Expr) IGraphEdgeDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g graphEdgeDo) Omit(cols ...field.Expr) IGraphEdgeDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g graphEdgeDo) Join(table schema.Tabler, on ...field.Expr) IGraphEdgeDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g graphEdgeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGraphEdgeDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g graphEdgeDo) RightJoin(table schema.Tabler, on ...field.Expr) IGraphEdgeDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g graphEdgeDo) Group(cols ...field.Expr) IGraphEdgeDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g graphEdgeDo) Having(conds ...gen.Condition) IGraphEdgeDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g graphEdgeDo) Limit(limit int) IGraphEdgeDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g graphEdgeDo) Offset(offset int) IGraphEdgeDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g graphEdgeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGraphEdgeDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g graphEdgeDo) Unscoped() IGraphEdgeDo {
	return g.withDO(g.DO.Unscoped())
}

func (g graphEdgeDo) Create(values ...*model.GraphEdge) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g graphEdgeDo) CreateInBatches(values []*model.GraphEdge, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g graphEdgeDo) Save(values ...*model.GraphEdge) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g graphEdgeDo) First() (*model.GraphEdge, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GraphEdge), nil
	}
}

func (g graphEdgeDo) Take() (*model.GraphEdge, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GraphEdge), nil
	}
}

func (g graphEdgeDo) Last() (*model.GraphEdge, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GraphEdge), nil
	}
}

func (g graphEdgeDo) Find() ([]*model.GraphEdge, error) {
	result, err := g.DO.Find()
	return result.([]*model.GraphEdge), err
}

func (g graphEdgeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GraphEdge, err error) {
	buf := make([]*model.GraphEdge, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g graphEdgeDo) FindInBatches(result *[]*model.GraphEdge, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g graphEdgeDo) Attrs(attrs ...field.AssignExpr) IGraphEdgeDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g graphEdgeDo) Assign(attrs ...field.AssignExpr) IGraphEdgeDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g graphEdgeDo) Joins(fields ...field.RelationField) IGraphEdgeDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g graphEdgeDo) Preload(fields ...field.RelationField) IGraphEdgeDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g graphEdgeDo) FirstOrInit() (*model.GraphEdge, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GraphEdge), nil
	}
}

func (g graphEdgeDo) FirstOrCreate() (*model.GraphEdge, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GraphEdge), nil
	}
}

func (g graphEdgeDo) FindByPage(offset int, limit int) (result []*model.GraphEdge, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g graphEdgeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g graphEdgeDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g graphEdgeDo) Delete(models ...*model.GraphEdge) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *graphEdgeDo) withDO(do gen.Dao) *graphEdgeDo {
	g.DO = *do.(*gen.DO)
	return g
}
