// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"scraperbot-front/internal/model"
)

func newGraphUIState(db *gorm.DB, opts ...gen.DOOption) graphUIState {
	_graphUIState := graphUIState{}

	_graphUIState.graphUIStateDo.UseDB(db, opts...)
	_graphUIState.graphUIStateDo.UseModel(&model.GraphUIState{})

	tableName := _graphUIState.graphUIStateDo.TableName()
	_graphUIState.ALL = field.NewAsterisk(tableName)
	_graphUIState.WorkspaceID = field.NewString(tableName, "workspace_id")
	_graphUIState.CollapsedNodeIdsJSON = field.NewString(tableName, "collapsed_node_ids_json")

	_graphUIState.fillFieldMap()

	return _graphUIState
}

type graphUIState struct {
	graphUIStateDo graphUIStateDo

	ALL                  field.Asterisk
	WorkspaceID          field.String
	CollapsedNodeIdsJSON field.String

	fieldMap map[string]field.Expr
}

func (g graphUIState) Table(newTableName string) *graphUIState {
	g.graphUIStateDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g graphUIState) As(alias string) *graphUIState {
	g.graphUIStateDo.DO = *(g.graphUIStateDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *graphUIState) updateTableName(table string) *graphUIState {
	g.ALL = field.NewAsterisk(table)
	g.WorkspaceID = field.NewString(table, "workspace_id")
	g.CollapsedNodeIdsJSON = field.NewString(table, "collapsed_node_ids_json")

	g.fillFieldMap()

	return g
}

func (g *graphUIState) WithContext(ctx context.Context) IGraphUIStateDo {
	return g.graphUIStateDo.WithContext(ctx)
}

func (g graphUIState) TableName() string { return g.graphUIStateDo.TableName() }

func (g graphUIState) Alias() string { return g.graphUIStateDo.Alias() }

func (g graphUIState) Columns(cols ...field.Expr) gen.Columns {
	return g.graphUIStateDo.Columns(cols...)
}

func (g *graphUIState) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *graphUIState) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 2)
	g.fieldMap["workspace_id"] = g.WorkspaceID
	g.fieldMap["collapsed_node_ids_json"] = g.CollapsedNodeIdsJSON
}

func (g graphUIState) clone(db *gorm.DB) graphUIState {
	g.graphUIStateDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g graphUIState) replaceDB(db *gorm.DB) graphUIState {
	g.graphUIStateDo.ReplaceDB(db)
	return g
}

type graphUIStateDo struct{ gen.DO }

type IGraphUIStateDo interface {
	gen.SubQuery
	Debug() IGraphUIStateDo
	WithContext(ctx context.Context) IGraphUIStateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGraphUIStateDo
	WriteDB() IGraphUIStateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGraphUIStateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGraphUIStateDo
	Not(conds ...gen.Condition) IGraphUIStateDo
	Or(conds ...gen.Condition) IGraphUIStateDo
	Select(conds ...field.Expr) IGraphUIStateDo
	Where(conds ...gen.Condition) IGraphUIStateDo
	Order(conds ...field.Expr) IGraphUIStateDo
	Distinct(cols ...field.Expr) IGraphUIStateDo
	Omit(cols ...field.Expr) IGraphUIStateDo
	Join(table schema.Tabler, on ...field.Expr) IGraphUIStateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGraphUIStateDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGraphUIStateDo
	Group(cols ...field.Expr) IGraphUIStateDo
	Having(conds ...gen.Condition) IGraphUIStateDo
	Limit(limit int) IGraphUIStateDo
	Offset(offset int) IGraphUIStateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGraphUIStateDo
	Unscoped() IGraphUIStateDo
	Create(values ...*model.GraphUIState) error
	CreateInBatches(values []*model.GraphUIState, batchSize int) error
	Save(values ...*model.GraphUIState) error
	First() (*model.GraphUIState, error)
	Take() (*model.GraphUIState, error)
	Last() (*model.GraphUIState, error)
	Find() ([]*model.GraphUIState, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GraphUIState, err error)
	FindInBatches(result *[]*model.GraphUIState, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.GraphUIState) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGraphUIStateDo
	Assign(attrs ...field.AssignExpr) IGraphUIStateDo
	Joins(fields ...field.RelationField) IGraphUIStateDo
	Preload(fields ...field.RelationField) IGraphUIStateDo
	FirstOrInit() (*model.GraphUIState, error)
	FirstOrCreate() (*model.GraphUIState, error)
	FindByPage(offset int, limit int) (result []*model.GraphUIState, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGraphUIStateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g graphUIStateDo) Debug() IGraphUIStateDo {
	return g.withDO(g.DO.Debug())
}

func (g graphUIStateDo) WithContext(ctx context.Context) IGraphUIStateDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g graphUIStateDo) ReadDB() IGraphUIStateDo {
	return g.Clauses(dbresolver.Read)
}

func (g graphUIStateDo) WriteDB() IGraphUIStateDo {
	return g.Clauses(dbresolver.Write)
}

func (g graphUIStateDo) Session(config *gorm.Session) IGraphUIStateDo {
	return g.withDO(g.DO.Session(config))
}

func (g graphUIStateDo) Clauses(conds ...clause.Expression) IGraphUIStateDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g graphUIStateDo) Returning(value interface{}, columns ...string) IGraphUIStateDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g graphUIStateDo) Not(conds ...gen.Condition) IGraphUIStateDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g graphUIStateDo) Or(conds ...gen.Condition) IGraphUIStateDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g graphUIStateDo) Select(conds ...field.Expr) IGraphUIStateDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g graphUIStateDo) Where(conds ...gen.Condition) IGraphUIStateDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g graphUIStateDo) Order(conds ...field.Expr) IGraphUIStateDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g graphUIStateDo) Distinct(cols ...field.Expr) IGraphUIStateDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g graphUIStateDo) Omit(cols ...field.Expr) IGraphUIStateDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g graphUIStateDo) Join(table schema.Tabler, on ...field.Expr) IGraphUIStateDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g graphUIStateDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGraphUIStateDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g graphUIStateDo) RightJoin(table schema.Tabler, on ...field.Expr) IGraphUIStateDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g graphUIStateDo) Group(cols ...field.Expr) IGraphUIStateDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g graphUIStateDo) Having(conds ...gen.Condition) IGraphUIStateDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g graphUIStateDo) Limit(limit int) IGraphUIStateDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g graphUIStateDo) Offset(offset int) IGraphUIStateDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g graphUIStateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGraphUIStateDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g graphUIStateDo) Unscoped() IGraphUIStateDo {
	return g.withDO(g.DO.Unscoped())
}

func (g graphUIStateDo) Create(values ...*model.GraphUIState) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g graphUIStateDo) CreateInBatches(values []*model.GraphUIState, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g graphUIStateDo) Save(values ...*model.GraphUIState) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g graphUIStateDo) First() (*model.GraphUIState, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GraphUIState), nil
	}
}

func (g graphUIStateDo) Take() (*model.GraphUIState, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GraphUIState), nil
	}
}

func (g graphUIStateDo) Last() (*model.GraphUIState, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GraphUIState), nil
	}
}

func (g graphUIStateDo) Find() ([]*model.GraphUIState, error) {
	result, err := g.DO.Find()
	return result.([]*model.GraphUIState), err
}

func (g graphUIStateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GraphUIState, err error) {
	buf := make([]*model.GraphUIState, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g graphUIStateDo) FindInBatches(result *[]*model.GraphUIState, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g graphUIStateDo) Attrs(attrs ...field.AssignExpr) IGraphUIStateDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g graphUIStateDo) Assign(attrs ...field.AssignExpr) IGraphUIStateDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g graphUIStateDo) Joins(fields ...field.RelationField) IGraphUIStateDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g graphUIStateDo) Preload(fields ...field.RelationField) IGraphUIStateDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g graphUIStateDo) FirstOrInit() (*model.GraphUIState, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GraphUIState), nil
	}
}

func (g graphUIStateDo) FirstOrCreate() (*model.GraphUIState, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GraphUIState), nil
	}
}

func (g graphUIStateDo) FindByPage(offset int, limit int) (result []*model.GraphUIState, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g graphUIStateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g graphUIStateDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g graphUIStateDo) Delete(models ...*model.GraphUIState) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *graphUIStateDo) withDO(do gen.Dao) *graphUIStateDo {
	g.DO = *do.(*gen.DO)
	return g
}
