// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"meguri-app/internal/model"
)

func newGraphNode(db *gorm.DB, opts ...gen.DOOption) graphNode {
	_graphNode := graphNode{}

	_graphNode.graphNodeDo.UseDB(db, opts...)
	_graphNode.graphNodeDo.UseModel(&model.GraphNode{})

	tableName := _graphNode.graphNodeDo.TableName()
	_graphNode.ALL = field.NewAsterisk(tableName)
	_graphNode.WorkspaceID = field.NewString(tableName, "workspace_id")
	_graphNode.ID = field.NewString(tableName, "id")
	_graphNode.URLNormalized = field.NewString(tableName, "url_normalized")
	_graphNode.Label = field.NewString(tableName, "label")
	_graphNode.PositionX = field.NewFloat64(tableName, "position_x")
	_graphNode.PositionY = field.NewFloat64(tableName, "position_y")
	_graphNode.UserPositioned = field.NewInt32(tableName, "user_positioned")
	_graphNode.NodeSettingsJSON = field.NewString(tableName, "node_settings_json")
	_graphNode.CrawlExclude = field.NewInt32(tableName, "crawl_exclude")
	_graphNode.Status = field.NewString(tableName, "status")
	_graphNode.LastError = field.NewString(tableName, "last_error")
	_graphNode.Origin = field.NewString(tableName, "origin")

	_graphNode.fillFieldMap()

	return _graphNode
}

type graphNode struct {
	graphNodeDo graphNodeDo

	ALL              field.Asterisk
	WorkspaceID      field.String
	ID               field.String
	URLNormalized    field.String
	Label            field.String
	PositionX        field.Float64
	PositionY        field.Float64
	UserPositioned   field.Int32
	NodeSettingsJSON field.String
	CrawlExclude     field.Int32
	Status           field.String
	LastError        field.String
	Origin           field.String

	fieldMap map[string]field.Expr
}

func (g graphNode) Table(newTableName string) *graphNode {
	g.graphNodeDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g graphNode) As(alias string) *graphNode {
	g.graphNodeDo.DO = *(g.graphNodeDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *graphNode) updateTableName(table string) *graphNode {
	g.ALL = field.NewAsterisk(table)
	g.WorkspaceID = field.NewString(table, "workspace_id")
	g.ID = field.NewString(table, "id")
	g.URLNormalized = field.NewString(table, "url_normalized")
	g.Label = field.NewString(table, "label")
	g.PositionX = field.NewFloat64(table, "position_x")
	g.PositionY = field.NewFloat64(table, "position_y")
	g.UserPositioned = field.NewInt32(table, "user_positioned")
	g.NodeSettingsJSON = field.NewString(table, "node_settings_json")
	g.CrawlExclude = field.NewInt32(table, "crawl_exclude")
	g.Status = field.NewString(table, "status")
	g.LastError = field.NewString(table, "last_error")
	g.Origin = field.NewString(table, "origin")

	g.fillFieldMap()

	return g
}

func (g *graphNode) WithContext(ctx context.Context) IGraphNodeDo {
	return g.graphNodeDo.WithContext(ctx)
}

func (g graphNode) TableName() string { return g.graphNodeDo.TableName() }

func (g graphNode) Alias() string { return g.graphNodeDo.Alias() }

func (g graphNode) Columns(cols ...field.Expr) gen.Columns { return g.graphNodeDo.Columns(cols...) }

func (g *graphNode) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *graphNode) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 12)
	g.fieldMap["workspace_id"] = g.WorkspaceID
	g.fieldMap["id"] = g.ID
	g.fieldMap["url_normalized"] = g.URLNormalized
	g.fieldMap["label"] = g.Label
	g.fieldMap["position_x"] = g.PositionX
	g.fieldMap["position_y"] = g.PositionY
	g.fieldMap["user_positioned"] = g.UserPositioned
	g.fieldMap["node_settings_json"] = g.NodeSettingsJSON
	g.fieldMap["crawl_exclude"] = g.CrawlExclude
	g.fieldMap["status"] = g.Status
	g.fieldMap["last_error"] = g.LastError
	g.fieldMap["origin"] = g.Origin
}

func (g graphNode) clone(db *gorm.DB) graphNode {
	g.graphNodeDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g graphNode) replaceDB(db *gorm.DB) graphNode {
	g.graphNodeDo.ReplaceDB(db)
	return g
}

type graphNodeDo struct{ gen.DO }

type IGraphNodeDo interface {
	gen.SubQuery
	Debug() IGraphNodeDo
	WithContext(ctx context.Context) IGraphNodeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGraphNodeDo
	WriteDB() IGraphNodeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGraphNodeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGraphNodeDo
	Not(conds ...gen.Condition) IGraphNodeDo
	Or(conds ...gen.Condition) IGraphNodeDo
	Select(conds ...field.Expr) IGraphNodeDo
	Where(conds ...gen.Condition) IGraphNodeDo
	Order(conds ...field.Expr) IGraphNodeDo
	Distinct(cols ...field.Expr) IGraphNodeDo
	Omit(cols ...field.Expr) IGraphNodeDo
	Join(table schema.Tabler, on ...field.Expr) IGraphNodeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGraphNodeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGraphNodeDo
	Group(cols ...field.Expr) IGraphNodeDo
	Having(conds ...gen.Condition) IGraphNodeDo
	Limit(limit int) IGraphNodeDo
	Offset(offset int) IGraphNodeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGraphNodeDo
	Unscoped() IGraphNodeDo
	Create(values ...*model.GraphNode) error
	CreateInBatches(values []*model.GraphNode, batchSize int) error
	Save(values ...*model.GraphNode) error
	First() (*model.GraphNode, error)
	Take() (*model.GraphNode, error)
	Last() (*model.GraphNode, error)
	Find() ([]*model.GraphNode, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GraphNode, err error)
	FindInBatches(result *[]*model.GraphNode, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.GraphNode) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGraphNodeDo
	Assign(attrs ...field.AssignExpr) IGraphNodeDo
	Joins(fields ...field.RelationField) IGraphNodeDo
	Preload(fields ...field.RelationField) IGraphNodeDo
	FirstOrInit() (*model.GraphNode, error)
	FirstOrCreate() (*model.GraphNode, error)
	FindByPage(offset int, limit int) (result []*model.GraphNode, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGraphNodeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g graphNodeDo) Debug() IGraphNodeDo {
	return g.withDO(g.DO.Debug())
}

func (g graphNodeDo) WithContext(ctx context.Context) IGraphNodeDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g graphNodeDo) ReadDB() IGraphNodeDo {
	return g.Clauses(dbresolver.Read)
}

func (g graphNodeDo) WriteDB() IGraphNodeDo {
	return g.Clauses(dbresolver.Write)
}

func (g graphNodeDo) Session(config *gorm.Session) IGraphNodeDo {
	return g.withDO(g.DO.Session(config))
}

func (g graphNodeDo) Clauses(conds ...clause.Expression) IGraphNodeDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g graphNodeDo) Returning(value interface{}, columns ...string) IGraphNodeDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g graphNodeDo) Not(conds ...gen.Condition) IGraphNodeDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g graphNodeDo) Or(conds ...gen.Condition) IGraphNodeDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g graphNodeDo) Select(conds ...field.Expr) IGraphNodeDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g graphNodeDo) Where(conds ...gen.Condition) IGraphNodeDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g graphNodeDo) Order(conds ...field.Expr) IGraphNodeDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g graphNodeDo) Distinct(cols ...field.Expr) IGraphNodeDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g graphNodeDo) Omit(cols ...field.Expr) IGraphNodeDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g graphNodeDo) Join(table schema.Tabler, on ...field.Expr) IGraphNodeDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g graphNodeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGraphNodeDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g graphNodeDo) RightJoin(table schema.Tabler, on ...field.Expr) IGraphNodeDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g graphNodeDo) Group(cols ...field.Expr) IGraphNodeDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g graphNodeDo) Having(conds ...gen.Condition) IGraphNodeDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g graphNodeDo) Limit(limit int) IGraphNodeDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g graphNodeDo) Offset(offset int) IGraphNodeDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g graphNodeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGraphNodeDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g graphNodeDo) Unscoped() IGraphNodeDo {
	return g.withDO(g.DO.Unscoped())
}

func (g graphNodeDo) Create(values ...*model.GraphNode) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g graphNodeDo) CreateInBatches(values []*model.GraphNode, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g graphNodeDo) Save(values ...*model.GraphNode) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g graphNodeDo) First() (*model.GraphNode, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GraphNode), nil
	}
}

func (g graphNodeDo) Take() (*model.GraphNode, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GraphNode), nil
	}
}

func (g graphNodeDo) Last() (*model.GraphNode, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GraphNode), nil
	}
}

func (g graphNodeDo) Find() ([]*model.GraphNode, error) {
	result, err := g.DO.Find()
	return result.([]*model.GraphNode), err
}

func (g graphNodeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GraphNode, err error) {
	buf := make([]*model.GraphNode, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g graphNodeDo) FindInBatches(result *[]*model.GraphNode, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g graphNodeDo) Attrs(attrs ...field.AssignExpr) IGraphNodeDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g graphNodeDo) Assign(attrs ...field.AssignExpr) IGraphNodeDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g graphNodeDo) Joins(fields ...field.RelationField) IGraphNodeDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g graphNodeDo) Preload(fields ...field.RelationField) IGraphNodeDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g graphNodeDo) FirstOrInit() (*model.GraphNode, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GraphNode), nil
	}
}

func (g graphNodeDo) FirstOrCreate() (*model.GraphNode, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GraphNode), nil
	}
}

func (g graphNodeDo) FindByPage(offset int, limit int) (result []*model.GraphNode, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g graphNodeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g graphNodeDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g graphNodeDo) Delete(models ...*model.GraphNode) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *graphNodeDo) withDO(do gen.Dao) *graphNodeDo {
	g.DO = *do.(*gen.DO)
	return g
}
