package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
)

var versionRE = regexp.MustCompile(`^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$`)

type versionInfo struct {
	AppVersion  string
	CoreVersion string
	FileVersion string
}

type versionJSON struct {
	AppVersion  string `json:"appVersion"`
	FileVersion string `json:"fileVersion"`
}

type infoJSON struct {
	Fixed struct {
		FileVersion string `json:"file_version"`
	} `json:"fixed"`
	Info map[string]struct {
		ProductVersion string `json:"ProductVersion"`
	} `json:"info"`
}

// repoRoot はリポジトリルート（go.work があるディレクトリ）を返す。
func repoRoot() (string, error) {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		return "", fmt.Errorf("caller path unavailable")
	}
	return filepath.Clean(filepath.Join(filepath.Dir(file), "../..")), nil
}

// parseVersion は X.Y.Z 形式の版文字列を検証して分解する。
func parseVersion(input string) (versionInfo, error) {
	if input == "" || strings.HasPrefix(input, "v") {
		return versionInfo{}, fmt.Errorf(`invalid version %q: use X.Y.Z without "v" prefix`, input)
	}
	match := versionRE.FindStringSubmatch(input)
	if match == nil {
		return versionInfo{}, fmt.Errorf(
			`invalid version %q: expected X.Y.Z (e.g. 1.0.0); pre-release suffixes are not supported`,
			input,
		)
	}
	appVersion := fmt.Sprintf("%s.%s.%s", match[1], match[2], match[3])
	return versionInfo{
		AppVersion:  appVersion,
		CoreVersion: appVersion,
		FileVersion: appVersion + ".0",
	}, nil
}

// setVersion は版を version.json と関連ファイルへ書き込む。更新したパス一覧を返す。
func setVersion(root, rawVersion string) ([]string, error) {
	info, err := parseVersion(rawVersion)
	if err != nil {
		return nil, err
	}

	paths := struct {
		versionJSON string
		configYml   string
		infoJson    string
		messagesTs  string
		versionNsis string
	}{
		versionJSON: filepath.Join(root, "tools/version-mng/version.json"),
		configYml:   filepath.Join(root, "front/build/config.yml"),
		infoJson:    filepath.Join(root, "front/build/windows/info.json"),
		messagesTs:  filepath.Join(root, "front/frontend/src/i18n/messages.ts"),
		versionNsis: filepath.Join(root, "front/build/windows/version-nsis.nsh"),
	}

	changed := make([]string, 0, 5)

	versionData, err := json.MarshalIndent(versionJSON{
		AppVersion:  info.AppVersion,
		FileVersion: info.FileVersion,
	}, "", "  ")
	if err != nil {
		return nil, err
	}
	versionData = append(versionData, '\n')
	if err := os.WriteFile(paths.versionJSON, versionData, 0o644); err != nil {
		return nil, err
	}
	changed = append(changed, paths.versionJSON)

	configYml, err := os.ReadFile(paths.configYml)
	if err != nil {
		return nil, err
	}
	updatedConfig, err := updateConfigYml(string(configYml), info.AppVersion)
	if err != nil {
		return nil, err
	}
	if err := os.WriteFile(paths.configYml, []byte(updatedConfig), 0o644); err != nil {
		return nil, err
	}
	changed = append(changed, paths.configYml)

	infoRaw, err := os.ReadFile(paths.infoJson)
	if err != nil {
		return nil, err
	}
	updatedInfo, err := updateInfoJSON(string(infoRaw), info.AppVersion, info.FileVersion)
	if err != nil {
		return nil, err
	}
	if err := os.WriteFile(paths.infoJson, []byte(updatedInfo), 0o644); err != nil {
		return nil, err
	}
	changed = append(changed, paths.infoJson)

	messagesTs, err := os.ReadFile(paths.messagesTs)
	if err != nil {
		return nil, err
	}
	updatedMessages, err := updateMessagesTS(string(messagesTs), info.AppVersion)
	if err != nil {
		return nil, err
	}
	if err := os.WriteFile(paths.messagesTs, []byte(updatedMessages), 0o644); err != nil {
		return nil, err
	}
	changed = append(changed, paths.messagesTs)

	nsisBody := fmt.Sprintf(
		"; Auto-generated by tools/version-mng — do not edit manually.\n!define INFO_PRODUCTVERSION_NUMERIC %q\n",
		info.CoreVersion,
	)
	if err := os.WriteFile(paths.versionNsis, []byte(nsisBody), 0o644); err != nil {
		return nil, err
	}
	changed = append(changed, paths.versionNsis)

	return changed, nil
}

func updateConfigYml(content, appVersion string) (string, error) {
	lines := strings.Split(content, "\n")
	inInfo := false
	for i, line := range lines {
		if line == "info:" {
			inInfo = true
			continue
		}
		if inInfo {
			if len(line) > 0 && !strings.HasPrefix(line, " ") && !strings.HasPrefix(line, "#") {
				break
			}
			if strings.HasPrefix(line, `  version: "`) {
				lines[i] = fmt.Sprintf(`  version: "%s"`, appVersion)
				return strings.Join(lines, "\n"), nil
			}
		}
	}
	return "", fmt.Errorf("config.yml: info.version line not found")
}

var messagesVersionRE = regexp.MustCompile(`(?m)^(\s*version:\s*)'(?:\\.|[^'\\])*'`)

func updateMessagesTS(content, appVersion string) (string, error) {
	if !messagesVersionRE.MatchString(content) {
		return "", fmt.Errorf("messages.ts: version line not found")
	}
	escaped := strings.ReplaceAll(appVersion, `\`, `\\`)
	escaped = strings.ReplaceAll(escaped, `'`, `\'`)
	replacement := fmt.Sprintf("$1'%s'", escaped)
	return messagesVersionRE.ReplaceAllString(content, replacement), nil
}

func updateInfoJSON(content, appVersion, fileVersion string) (string, error) {
	var data infoJSON
	if err := json.Unmarshal([]byte(content), &data); err != nil {
		return "", err
	}
	data.Fixed.FileVersion = fileVersion
	block, ok := data.Info["0000"]
	if !ok {
		return "", fmt.Errorf("info.json: info.0000 block not found")
	}
	block.ProductVersion = appVersion
	data.Info["0000"] = block

	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "\t")
	if err := enc.Encode(data); err != nil {
		return "", err
	}
	return buf.String(), nil
}
