// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";

/**
 * AppendNodeResultRequest は結果行追加。
 */
export class AppendNodeResultRequest {
    "workspaceId": string;
    "runId": string;
    "nodeId": string;
    "url": string;
    "markdown"?: string;
    "linksJson"?: string;
    "metadataJson"?: string;
    "error"?: string;
    "fetchedAt": string;
    "contentHash"?: string;

    /** Creates a new AppendNodeResultRequest instance. */
    constructor($$source: Partial<AppendNodeResultRequest> = {}) {
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }
        if (!("runId" in $$source)) {
            this["runId"] = "";
        }
        if (!("nodeId" in $$source)) {
            this["nodeId"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("fetchedAt" in $$source)) {
            this["fetchedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppendNodeResultRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AppendNodeResultRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppendNodeResultRequest($$parsedSource as Partial<AppendNodeResultRequest>);
    }
}

/**
 * BeginCrawlRunRequest は crawl run 開始。
 */
export class BeginCrawlRunRequest {
    "workspaceId": string;
    "runId": string;
    "mode": number;
    "startedAt": string;

    /** Creates a new BeginCrawlRunRequest instance. */
    constructor($$source: Partial<BeginCrawlRunRequest> = {}) {
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }
        if (!("runId" in $$source)) {
            this["runId"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = 0;
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BeginCrawlRunRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): BeginCrawlRunRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BeginCrawlRunRequest($$parsedSource as Partial<BeginCrawlRunRequest>);
    }
}

/**
 * CrawlResultDTO はノード結果プレビュー。
 */
export class CrawlResultDTO {
    "url": string;
    "markdown"?: string;
    "links"?: string[];
    "metadata"?: { [_ in string]?: string };

    /** Creates a new CrawlResultDTO instance. */
    constructor($$source: Partial<CrawlResultDTO> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CrawlResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): CrawlResultDTO {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("links" in $$parsedSource) {
            $$parsedSource["links"] = $$createField2_0($$parsedSource["links"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField3_0($$parsedSource["metadata"]);
        }
        return new CrawlResultDTO($$parsedSource as Partial<CrawlResultDTO>);
    }
}

/**
 * FinishCrawlRunRequest は crawl run 終了。
 */
export class FinishCrawlRunRequest {
    "workspaceId": string;
    "runId": string;
    "status": string;
    "finishedAt": string;
    "summaryJson"?: json$0.RawMessage;
    "errorMessage"?: string;

    /** Creates a new FinishCrawlRunRequest instance. */
    constructor($$source: Partial<FinishCrawlRunRequest> = {}) {
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }
        if (!("runId" in $$source)) {
            this["runId"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("finishedAt" in $$source)) {
            this["finishedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FinishCrawlRunRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): FinishCrawlRunRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FinishCrawlRunRequest($$parsedSource as Partial<FinishCrawlRunRequest>);
    }
}

/**
 * GraphEdgeDTO は Wails 公開エッジ。
 */
export class GraphEdgeDTO {
    "id": string;
    "source": string;
    "target": string;

    /** Creates a new GraphEdgeDTO instance. */
    constructor($$source: Partial<GraphEdgeDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphEdgeDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphEdgeDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GraphEdgeDTO($$parsedSource as Partial<GraphEdgeDTO>);
    }
}

/**
 * GraphNodeDTO は Wails 公開ノード。
 */
export class GraphNodeDTO {
    "id": string;
    "urlNormalized": string;
    "label": string;
    "position": PositionDTO;
    "userPositioned"?: boolean;
    "nodeSettings": json$0.RawMessage;
    "crawlExclude": boolean;
    "status": string;
    "lastError"?: string;
    "lastResult"?: CrawlResultDTO | null;

    /** Creates a new GraphNodeDTO instance. */
    constructor($$source: Partial<GraphNodeDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("urlNormalized" in $$source)) {
            this["urlNormalized"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("position" in $$source)) {
            this["position"] = (new PositionDTO());
        }
        if (!("nodeSettings" in $$source)) {
            this["nodeSettings"] = null;
        }
        if (!("crawlExclude" in $$source)) {
            this["crawlExclude"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphNodeDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphNodeDTO {
        const $$createField3_0 = $$createType2;
        const $$createField9_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("position" in $$parsedSource) {
            $$parsedSource["position"] = $$createField3_0($$parsedSource["position"]);
        }
        if ("lastResult" in $$parsedSource) {
            $$parsedSource["lastResult"] = $$createField9_0($$parsedSource["lastResult"]);
        }
        return new GraphNodeDTO($$parsedSource as Partial<GraphNodeDTO>);
    }
}

/**
 * MergeResultsResponseDTO はマージ結果。
 */
export class MergeResultsResponseDTO {
    "merged": string;
    "format": string;
    "nodeCount": number;

    /** Creates a new MergeResultsResponseDTO instance. */
    constructor($$source: Partial<MergeResultsResponseDTO> = {}) {
        if (!("merged" in $$source)) {
            this["merged"] = "";
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("nodeCount" in $$source)) {
            this["nodeCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergeResultsResponseDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): MergeResultsResponseDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MergeResultsResponseDTO($$parsedSource as Partial<MergeResultsResponseDTO>);
    }
}

/**
 * NodeDiffDTO は差分ノード。
 */
export class NodeDiffDTO {
    "nodeId": string;
    "url": string;
    "kinds": string[];

    /** Creates a new NodeDiffDTO instance. */
    constructor($$source: Partial<NodeDiffDTO> = {}) {
        if (!("nodeId" in $$source)) {
            this["nodeId"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("kinds" in $$source)) {
            this["kinds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeDiffDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): NodeDiffDTO {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("kinds" in $$parsedSource) {
            $$parsedSource["kinds"] = $$createField2_0($$parsedSource["kinds"]);
        }
        return new NodeDiffDTO($$parsedSource as Partial<NodeDiffDTO>);
    }
}

/**
 * OpenScrbResponse は .scrb インポート結果。
 */
export class OpenScrbResponse {
    "workspaceId": string;

    /** Creates a new OpenScrbResponse instance. */
    constructor($$source: Partial<OpenScrbResponse> = {}) {
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenScrbResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenScrbResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenScrbResponse($$parsedSource as Partial<OpenScrbResponse>);
    }
}

/**
 * PatchGraphNodeStatusRequest はノード status 更新。
 */
export class PatchGraphNodeStatusRequest {
    "workspaceId": string;
    "nodeId": string;
    "status": string;
    "lastError"?: string;

    /** Creates a new PatchGraphNodeStatusRequest instance. */
    constructor($$source: Partial<PatchGraphNodeStatusRequest> = {}) {
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }
        if (!("nodeId" in $$source)) {
            this["nodeId"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PatchGraphNodeStatusRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): PatchGraphNodeStatusRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PatchGraphNodeStatusRequest($$parsedSource as Partial<PatchGraphNodeStatusRequest>);
    }
}

/**
 * PositionDTO はグラフノード座標。
 */
export class PositionDTO {
    "x": number;
    "y": number;

    /** Creates a new PositionDTO instance. */
    constructor($$source: Partial<PositionDTO> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PositionDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): PositionDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PositionDTO($$parsedSource as Partial<PositionDTO>);
    }
}

/**
 * SaveSettingsResponseDTO は設定保存レスポンス。
 */
export class SaveSettingsResponseDTO {
    "ok": boolean;
    "scope": string;

    /** Creates a new SaveSettingsResponseDTO instance. */
    constructor($$source: Partial<SaveSettingsResponseDTO> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("scope" in $$source)) {
            this["scope"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveSettingsResponseDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveSettingsResponseDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveSettingsResponseDTO($$parsedSource as Partial<SaveSettingsResponseDTO>);
    }
}

/**
 * WorkspaceDTO は Wails 公開ワークスペース。
 */
export class WorkspaceDTO {
    "id": string;
    "name": string;
    "seedUrl": string;
    "settings": json$0.RawMessage;
    "exclude_urls": string[];
    "nodes": GraphNodeDTO[];
    "edges": GraphEdgeDTO[];
    "graphLayoutDirection": string;
    "domainSettings": { [_ in string]?: json$0.RawMessage };
    "baselineRunId"?: string;
    "collapsedNodeIds"?: string[];
    "expandedDetailNodeIds"?: string[];
    "createdAt"?: string;

    /** Creates a new WorkspaceDTO instance. */
    constructor($$source: Partial<WorkspaceDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("seedUrl" in $$source)) {
            this["seedUrl"] = "";
        }
        if (!("settings" in $$source)) {
            this["settings"] = null;
        }
        if (!("exclude_urls" in $$source)) {
            this["exclude_urls"] = [];
        }
        if (!("nodes" in $$source)) {
            this["nodes"] = [];
        }
        if (!("edges" in $$source)) {
            this["edges"] = [];
        }
        if (!("graphLayoutDirection" in $$source)) {
            this["graphLayoutDirection"] = "";
        }
        if (!("domainSettings" in $$source)) {
            this["domainSettings"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceDTO {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType6;
        const $$createField6_0 = $$createType8;
        const $$createField8_0 = $$createType9;
        const $$createField10_0 = $$createType0;
        const $$createField11_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("exclude_urls" in $$parsedSource) {
            $$parsedSource["exclude_urls"] = $$createField4_0($$parsedSource["exclude_urls"]);
        }
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField5_0($$parsedSource["nodes"]);
        }
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField6_0($$parsedSource["edges"]);
        }
        if ("domainSettings" in $$parsedSource) {
            $$parsedSource["domainSettings"] = $$createField8_0($$parsedSource["domainSettings"]);
        }
        if ("collapsedNodeIds" in $$parsedSource) {
            $$parsedSource["collapsedNodeIds"] = $$createField10_0($$parsedSource["collapsedNodeIds"]);
        }
        if ("expandedDetailNodeIds" in $$parsedSource) {
            $$parsedSource["expandedDetailNodeIds"] = $$createField11_0($$parsedSource["expandedDetailNodeIds"]);
        }
        return new WorkspaceDTO($$parsedSource as Partial<WorkspaceDTO>);
    }
}

/**
 * WorkspaceDiffDTO は WS 差分。
 */
export class WorkspaceDiffDTO {
    "workspaceId": string;
    "hasDiff": boolean;
    "baselineRunId"?: string;
    "nodes": NodeDiffDTO[];
    "summary": {"content": number, "links": number, "fetch": number};

    /** Creates a new WorkspaceDiffDTO instance. */
    constructor($$source: Partial<WorkspaceDiffDTO> = {}) {
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }
        if (!("hasDiff" in $$source)) {
            this["hasDiff"] = false;
        }
        if (!("nodes" in $$source)) {
            this["nodes"] = [];
        }
        if (!("summary" in $$source)) {
            this["summary"] = {"content": 0, "links": 0, "fetch": 0};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceDiffDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceDiffDTO {
        const $$createField3_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField3_0($$parsedSource["nodes"]);
        }
        return new WorkspaceDiffDTO($$parsedSource as Partial<WorkspaceDiffDTO>);
    }
}

/**
 * WorkspaceListItemDTO は WS 一覧行。
 */
export class WorkspaceListItemDTO {
    "id": string;
    "name": string;
    "updatedAt": string;

    /** Creates a new WorkspaceListItemDTO instance. */
    constructor($$source: Partial<WorkspaceListItemDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceListItemDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceListItemDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceListItemDTO($$parsedSource as Partial<WorkspaceListItemDTO>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = PositionDTO.createFrom;
const $$createType3 = CrawlResultDTO.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = GraphNodeDTO.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = GraphEdgeDTO.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Map($Create.Any, $Create.Any);
const $$createType10 = NodeDiffDTO.createFrom;
const $$createType11 = $Create.Array($$createType10);
