// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";

/**
 * AppendNodeResultRequest は結果行追加。
 */
export class AppendNodeResultRequest {
    "workspaceId": string;
    "runId": string;
    "nodeId": string;
    "url": string;
    "markdown"?: string;
    "html"?: string;
    "rawHtml"?: string;
    "linksJson"?: string;
    "metadataJson"?: string;
    "error"?: string;
    "fetchedAt": string;
    "contentHash"?: string;

    /** Creates a new AppendNodeResultRequest instance. */
    constructor($$source: Partial<AppendNodeResultRequest> = {}) {
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }
        if (!("runId" in $$source)) {
            this["runId"] = "";
        }
        if (!("nodeId" in $$source)) {
            this["nodeId"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("fetchedAt" in $$source)) {
            this["fetchedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppendNodeResultRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AppendNodeResultRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppendNodeResultRequest($$parsedSource as Partial<AppendNodeResultRequest>);
    }
}

/**
 * BeginCrawlRunRequest は crawl run 開始。
 */
export class BeginCrawlRunRequest {
    "workspaceId": string;
    "runId": string;
    "mode": number;
    "startedAt": string;

    /** Creates a new BeginCrawlRunRequest instance. */
    constructor($$source: Partial<BeginCrawlRunRequest> = {}) {
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }
        if (!("runId" in $$source)) {
            this["runId"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = 0;
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BeginCrawlRunRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): BeginCrawlRunRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BeginCrawlRunRequest($$parsedSource as Partial<BeginCrawlRunRequest>);
    }
}

/**
 * CrawlResultDTO はノード結果プレビュー。
 */
export class CrawlResultDTO {
    "url": string;
    "markdown"?: string;
    "html"?: string;
    "rawHtml"?: string;
    "jsonBody"?: string;
    "links"?: string[];
    "metadata"?: { [_ in string]?: string };
    "manuallyEdited"?: boolean;

    /** Creates a new CrawlResultDTO instance. */
    constructor($$source: Partial<CrawlResultDTO> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CrawlResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): CrawlResultDTO {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("links" in $$parsedSource) {
            $$parsedSource["links"] = $$createField5_0($$parsedSource["links"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField6_0($$parsedSource["metadata"]);
        }
        return new CrawlResultDTO($$parsedSource as Partial<CrawlResultDTO>);
    }
}

/**
 * FinishCrawlRunRequest は crawl run 終了。
 */
export class FinishCrawlRunRequest {
    "workspaceId": string;
    "runId": string;
    "status": string;
    "finishedAt": string;
    "summaryJson"?: json$0.RawMessage;
    "errorMessage"?: string;

    /** Creates a new FinishCrawlRunRequest instance. */
    constructor($$source: Partial<FinishCrawlRunRequest> = {}) {
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }
        if (!("runId" in $$source)) {
            this["runId"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("finishedAt" in $$source)) {
            this["finishedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FinishCrawlRunRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): FinishCrawlRunRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FinishCrawlRunRequest($$parsedSource as Partial<FinishCrawlRunRequest>);
    }
}

/**
 * GraphEdgeDTO は Wails 公開エッジ。
 */
export class GraphEdgeDTO {
    "id": string;
    "source": string;
    "target": string;

    /** Creates a new GraphEdgeDTO instance. */
    constructor($$source: Partial<GraphEdgeDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphEdgeDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphEdgeDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GraphEdgeDTO($$parsedSource as Partial<GraphEdgeDTO>);
    }
}

/**
 * GraphNodeDTO は Wails 公開ノード。
 */
export class GraphNodeDTO {
    "id": string;
    "urlNormalized": string;
    "label": string;
    "position": PositionDTO;
    "userPositioned"?: boolean;
    "nodeSettings": json$0.RawMessage;
    "crawlExclude": boolean;
    "origin": string;
    "status": string;
    "lastError"?: string;
    "lastResult"?: CrawlResultDTO | null;

    /** Creates a new GraphNodeDTO instance. */
    constructor($$source: Partial<GraphNodeDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("urlNormalized" in $$source)) {
            this["urlNormalized"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("position" in $$source)) {
            this["position"] = (new PositionDTO());
        }
        if (!("nodeSettings" in $$source)) {
            this["nodeSettings"] = null;
        }
        if (!("crawlExclude" in $$source)) {
            this["crawlExclude"] = false;
        }
        if (!("origin" in $$source)) {
            this["origin"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphNodeDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphNodeDTO {
        const $$createField3_0 = $$createType2;
        const $$createField10_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("position" in $$parsedSource) {
            $$parsedSource["position"] = $$createField3_0($$parsedSource["position"]);
        }
        if ("lastResult" in $$parsedSource) {
            $$parsedSource["lastResult"] = $$createField10_0($$parsedSource["lastResult"]);
        }
        return new GraphNodeDTO($$parsedSource as Partial<GraphNodeDTO>);
    }
}

/**
 * MaximizedNodeResultRequest は最大化ウィンドウ表示用スナップショット。
 */
export class MaximizedNodeResultRequest {
    "title": string;
    "activeFormat": string;
    "markdownView": string;
    "formats": string[];
    "result": CrawlResultDTO;

    /** Creates a new MaximizedNodeResultRequest instance. */
    constructor($$source: Partial<MaximizedNodeResultRequest> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("activeFormat" in $$source)) {
            this["activeFormat"] = "";
        }
        if (!("markdownView" in $$source)) {
            this["markdownView"] = "";
        }
        if (!("formats" in $$source)) {
            this["formats"] = [];
        }
        if (!("result" in $$source)) {
            this["result"] = (new CrawlResultDTO());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MaximizedNodeResultRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): MaximizedNodeResultRequest {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("formats" in $$parsedSource) {
            $$parsedSource["formats"] = $$createField3_0($$parsedSource["formats"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField4_0($$parsedSource["result"]);
        }
        return new MaximizedNodeResultRequest($$parsedSource as Partial<MaximizedNodeResultRequest>);
    }
}

/**
 * MergeResultsResponseDTO はマージ結果。
 */
export class MergeResultsResponseDTO {
    "merged": string;
    "format": string;
    "nodeCount": number;

    /** Creates a new MergeResultsResponseDTO instance. */
    constructor($$source: Partial<MergeResultsResponseDTO> = {}) {
        if (!("merged" in $$source)) {
            this["merged"] = "";
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("nodeCount" in $$source)) {
            this["nodeCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergeResultsResponseDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): MergeResultsResponseDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MergeResultsResponseDTO($$parsedSource as Partial<MergeResultsResponseDTO>);
    }
}

/**
 * NodeDiffDTO は差分ノード。
 */
export class NodeDiffDTO {
    "nodeId": string;
    "url": string;
    "kinds": string[];

    /** Creates a new NodeDiffDTO instance. */
    constructor($$source: Partial<NodeDiffDTO> = {}) {
        if (!("nodeId" in $$source)) {
            this["nodeId"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("kinds" in $$source)) {
            this["kinds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeDiffDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): NodeDiffDTO {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("kinds" in $$parsedSource) {
            $$parsedSource["kinds"] = $$createField2_0($$parsedSource["kinds"]);
        }
        return new NodeDiffDTO($$parsedSource as Partial<NodeDiffDTO>);
    }
}

/**
 * NodePositionPatchDTO はノード座標の部分更新。
 */
export class NodePositionPatchDTO {
    "nodeId": string;
    "position": PositionDTO;
    "userPositioned": boolean;

    /** Creates a new NodePositionPatchDTO instance. */
    constructor($$source: Partial<NodePositionPatchDTO> = {}) {
        if (!("nodeId" in $$source)) {
            this["nodeId"] = "";
        }
        if (!("position" in $$source)) {
            this["position"] = (new PositionDTO());
        }
        if (!("userPositioned" in $$source)) {
            this["userPositioned"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodePositionPatchDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): NodePositionPatchDTO {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("position" in $$parsedSource) {
            $$parsedSource["position"] = $$createField1_0($$parsedSource["position"]);
        }
        return new NodePositionPatchDTO($$parsedSource as Partial<NodePositionPatchDTO>);
    }
}

/**
 * OpenScrbResponse は .scrb インポート結果。
 */
export class OpenScrbResponse {
    "workspaceId": string;

    /** Creates a new OpenScrbResponse instance. */
    constructor($$source: Partial<OpenScrbResponse> = {}) {
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenScrbResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenScrbResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenScrbResponse($$parsedSource as Partial<OpenScrbResponse>);
    }
}

/**
 * PatchGraphNodePositionsRequest はノード座標のバッチ部分更新。
 */
export class PatchGraphNodePositionsRequest {
    "workspaceId": string;
    "updates": NodePositionPatchDTO[];

    /** Creates a new PatchGraphNodePositionsRequest instance. */
    constructor($$source: Partial<PatchGraphNodePositionsRequest> = {}) {
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }
        if (!("updates" in $$source)) {
            this["updates"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PatchGraphNodePositionsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): PatchGraphNodePositionsRequest {
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("updates" in $$parsedSource) {
            $$parsedSource["updates"] = $$createField1_0($$parsedSource["updates"]);
        }
        return new PatchGraphNodePositionsRequest($$parsedSource as Partial<PatchGraphNodePositionsRequest>);
    }
}

/**
 * PatchGraphNodeStatusRequest はノード status 更新。
 */
export class PatchGraphNodeStatusRequest {
    "workspaceId": string;
    "nodeId": string;
    "status": string;
    "lastError"?: string;

    /** Creates a new PatchGraphNodeStatusRequest instance. */
    constructor($$source: Partial<PatchGraphNodeStatusRequest> = {}) {
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }
        if (!("nodeId" in $$source)) {
            this["nodeId"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PatchGraphNodeStatusRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): PatchGraphNodeStatusRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PatchGraphNodeStatusRequest($$parsedSource as Partial<PatchGraphNodeStatusRequest>);
    }
}

/**
 * PositionDTO はグラフノード座標。
 */
export class PositionDTO {
    "x": number;
    "y": number;

    /** Creates a new PositionDTO instance. */
    constructor($$source: Partial<PositionDTO> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PositionDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): PositionDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PositionDTO($$parsedSource as Partial<PositionDTO>);
    }
}

/**
 * RobotsTxtInfoDTO は robots.txt 取得結果。
 */
export class RobotsTxtInfoDTO {
    "host": string;
    "status": string;
    "statusCode": number;
    "body": string;
    "error"?: string;

    /** Creates a new RobotsTxtInfoDTO instance. */
    constructor($$source: Partial<RobotsTxtInfoDTO> = {}) {
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("statusCode" in $$source)) {
            this["statusCode"] = 0;
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RobotsTxtInfoDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): RobotsTxtInfoDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RobotsTxtInfoDTO($$parsedSource as Partial<RobotsTxtInfoDTO>);
    }
}

/**
 * SaveSettingsResponseDTO は設定保存レスポンス。
 */
export class SaveSettingsResponseDTO {
    "ok": boolean;
    "scope": string;

    /** Creates a new SaveSettingsResponseDTO instance. */
    constructor($$source: Partial<SaveSettingsResponseDTO> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("scope" in $$source)) {
            this["scope"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveSettingsResponseDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveSettingsResponseDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveSettingsResponseDTO($$parsedSource as Partial<SaveSettingsResponseDTO>);
    }
}

/**
 * StartCrawlRequest はクロール開始 RPC 入力。
 */
export class StartCrawlRequest {
    "runId": string;
    "workspaceId": string;
    "mode": number;
    "startNodeId"?: string;
    "nodeIds"?: string[];
    "rescrapeExisting": boolean;
    "appDefaults": json$0.RawMessage;
    "workspace": WorkspaceDTO;

    /** Creates a new StartCrawlRequest instance. */
    constructor($$source: Partial<StartCrawlRequest> = {}) {
        if (!("runId" in $$source)) {
            this["runId"] = "";
        }
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = 0;
        }
        if (!("rescrapeExisting" in $$source)) {
            this["rescrapeExisting"] = false;
        }
        if (!("appDefaults" in $$source)) {
            this["appDefaults"] = null;
        }
        if (!("workspace" in $$source)) {
            this["workspace"] = (new WorkspaceDTO());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartCrawlRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartCrawlRequest {
        const $$createField4_0 = $$createType0;
        const $$createField7_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodeIds" in $$parsedSource) {
            $$parsedSource["nodeIds"] = $$createField4_0($$parsedSource["nodeIds"]);
        }
        if ("workspace" in $$parsedSource) {
            $$parsedSource["workspace"] = $$createField7_0($$parsedSource["workspace"]);
        }
        return new StartCrawlRequest($$parsedSource as Partial<StartCrawlRequest>);
    }
}

/**
 * UpdateNodeResultPatchDTO はノード結果の部分更新フィールド。
 */
export class UpdateNodeResultPatchDTO {
    "markdown"?: string | null;
    "html"?: string | null;
    "rawHtml"?: string | null;
    "jsonBody"?: string | null;

    /** Creates a new UpdateNodeResultPatchDTO instance. */
    constructor($$source: Partial<UpdateNodeResultPatchDTO> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateNodeResultPatchDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateNodeResultPatchDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateNodeResultPatchDTO($$parsedSource as Partial<UpdateNodeResultPatchDTO>);
    }
}

/**
 * UpdateNodeResultRequest はノード結果手動編集の保存リクエスト。
 */
export class UpdateNodeResultRequest {
    "workspaceId": string;
    "nodeId": string;
    "patch": UpdateNodeResultPatchDTO;

    /** Creates a new UpdateNodeResultRequest instance. */
    constructor($$source: Partial<UpdateNodeResultRequest> = {}) {
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }
        if (!("nodeId" in $$source)) {
            this["nodeId"] = "";
        }
        if (!("patch" in $$source)) {
            this["patch"] = (new UpdateNodeResultPatchDTO());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateNodeResultRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateNodeResultRequest {
        const $$createField2_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("patch" in $$parsedSource) {
            $$parsedSource["patch"] = $$createField2_0($$parsedSource["patch"]);
        }
        return new UpdateNodeResultRequest($$parsedSource as Partial<UpdateNodeResultRequest>);
    }
}

/**
 * UpsertDiscoveredGraphRequest は crawl 中に発見したノードとエッジを永続化する。
 */
export class UpsertDiscoveredGraphRequest {
    "workspaceId": string;
    "sourceId": string;
    "targetId": string;
    "targetUrl": string;

    /** Creates a new UpsertDiscoveredGraphRequest instance. */
    constructor($$source: Partial<UpsertDiscoveredGraphRequest> = {}) {
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }
        if (!("sourceId" in $$source)) {
            this["sourceId"] = "";
        }
        if (!("targetId" in $$source)) {
            this["targetId"] = "";
        }
        if (!("targetUrl" in $$source)) {
            this["targetUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpsertDiscoveredGraphRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpsertDiscoveredGraphRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpsertDiscoveredGraphRequest($$parsedSource as Partial<UpsertDiscoveredGraphRequest>);
    }
}

/**
 * WorkspaceDTO は Wails 公開ワークスペース。
 */
export class WorkspaceDTO {
    "id": string;
    "name": string;
    "seedUrl": string;
    "settings": json$0.RawMessage;
    "exclude_urls": string[];
    "nodes": GraphNodeDTO[];
    "edges": GraphEdgeDTO[];
    "graphLayoutDirection": string;
    "baselineRunId"?: string;
    "collapsedNodeIds"?: string[];
    "expandedDetailNodeIds"?: string[];
    "createdAt"?: string;

    /** Creates a new WorkspaceDTO instance. */
    constructor($$source: Partial<WorkspaceDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("seedUrl" in $$source)) {
            this["seedUrl"] = "";
        }
        if (!("settings" in $$source)) {
            this["settings"] = null;
        }
        if (!("exclude_urls" in $$source)) {
            this["exclude_urls"] = [];
        }
        if (!("nodes" in $$source)) {
            this["nodes"] = [];
        }
        if (!("edges" in $$source)) {
            this["edges"] = [];
        }
        if (!("graphLayoutDirection" in $$source)) {
            this["graphLayoutDirection"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceDTO {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType10;
        const $$createField6_0 = $$createType12;
        const $$createField9_0 = $$createType0;
        const $$createField10_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("exclude_urls" in $$parsedSource) {
            $$parsedSource["exclude_urls"] = $$createField4_0($$parsedSource["exclude_urls"]);
        }
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField5_0($$parsedSource["nodes"]);
        }
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField6_0($$parsedSource["edges"]);
        }
        if ("collapsedNodeIds" in $$parsedSource) {
            $$parsedSource["collapsedNodeIds"] = $$createField9_0($$parsedSource["collapsedNodeIds"]);
        }
        if ("expandedDetailNodeIds" in $$parsedSource) {
            $$parsedSource["expandedDetailNodeIds"] = $$createField10_0($$parsedSource["expandedDetailNodeIds"]);
        }
        return new WorkspaceDTO($$parsedSource as Partial<WorkspaceDTO>);
    }
}

/**
 * WorkspaceDiffDTO は WS 差分。
 */
export class WorkspaceDiffDTO {
    "workspaceId": string;
    "hasDiff": boolean;
    "baselineRunId"?: string;
    "nodes": NodeDiffDTO[];
    "summary": {"content": number, "links": number, "fetch": number};

    /** Creates a new WorkspaceDiffDTO instance. */
    constructor($$source: Partial<WorkspaceDiffDTO> = {}) {
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }
        if (!("hasDiff" in $$source)) {
            this["hasDiff"] = false;
        }
        if (!("nodes" in $$source)) {
            this["nodes"] = [];
        }
        if (!("summary" in $$source)) {
            this["summary"] = {"content": 0, "links": 0, "fetch": 0};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceDiffDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceDiffDTO {
        const $$createField3_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField3_0($$parsedSource["nodes"]);
        }
        return new WorkspaceDiffDTO($$parsedSource as Partial<WorkspaceDiffDTO>);
    }
}

/**
 * WorkspaceListItemDTO は WS 一覧行。
 */
export class WorkspaceListItemDTO {
    "id": string;
    "name": string;
    "updatedAt": string;

    /** Creates a new WorkspaceListItemDTO instance. */
    constructor($$source: Partial<WorkspaceListItemDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceListItemDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceListItemDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceListItemDTO($$parsedSource as Partial<WorkspaceListItemDTO>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = PositionDTO.createFrom;
const $$createType3 = CrawlResultDTO.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = NodePositionPatchDTO.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = WorkspaceDTO.createFrom;
const $$createType8 = UpdateNodeResultPatchDTO.createFrom;
const $$createType9 = GraphNodeDTO.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = GraphEdgeDTO.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = NodeDiffDTO.createFrom;
const $$createType14 = $Create.Array($$createType13);
